"""
Benchmark accuracy_run.py for timm/mobilenetv3_small_100.lamb_in1k (image classification).
Generated by benchmark-runner (手写 timm 路线，非 transformers 模板). Dimension 2 (accuracy .pt) + 3 (perf) + 4 (trace, required).

两步依次执行:
  Step 1: 单样本 -> trace_*.json + benchmark_metrics_*.json (性能分析)
  Step 2: 全样本 -> outputs_*.pt (精度测试 + top-1/top-5 logits 画像)

Usage:
    uv run python accuracy_run.py                    # Tier1: 随机权重 (config)
    uv run python accuracy_run.py --use-pretrained   # Tier2: 加载预训练权重 (hf-hub)
    uv run python accuracy_run.py --cpu              # 强制 CPU 推理 (禁用 NPU/CUDA)

Model Type: vision_classification (timm)
Recommended Dataset: cifar100 (缺失时降级合成随机图像)

Host notes (2x Ascend910):
- 本机严禁设置 ASCEND_RT_VISIBLE_DEVICES（会导致 aclInit error 107001），
  选卡一律使用 torch.npu.set_device()，并按 mem_get_info 自动选择空闲卡。
"""

import argparse
import json
import os
import random
import shutil
import time
from datetime import datetime
from pathlib import Path

# HuggingFace 镜像（国内直连 huggingface.co 不通）
# 必须在导入 timm / huggingface_hub 之前设置，否则 endpoint 会被固化为默认值
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")
os.environ.setdefault("HF_HUB_DISABLE_XET", "1")

# 缓存固定在本 adaptation 内，避免污染项目根 models/
CACHE_DIR = (Path(__file__).resolve().parent / "models").as_posix()
os.environ.setdefault("HF_HOME", CACHE_DIR)
os.environ.setdefault("HF_HUB_CACHE", CACHE_DIR)

import numpy as np
import timm
import torch
import torch.nn.functional as F
from datasets import load_from_disk

MODEL_ID = "timm/mobilenetv3_small_100.lamb_in1k"
ARCH = "mobilenetv3_small_100"  # timm registry 架构名（.lamb_in1k 是预训练 tag）
NUM_CLASSES = 1000
INPUT_SIZE = (3, 224, 224)
# ImageNet 归一化（与 demo.py 保持一致）
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

# 数据集配置：优先 adaptation 本地 datasets/（所有副作用仅限 adaptation_path），
# 其次只读尝试项目级 datasets/，最后降级合成随机图像。
ADAPT_DIR = Path(__file__).resolve().parent
LOCAL_DATASET_DIR = ADAPT_DIR / "datasets"
PROJECT_DATASET_DIR = ADAPT_DIR.parent.parent / "datasets"


def load_benchmark_images() -> tuple[list[torch.Tensor], str]:
    """加载测试图像数据集，返回 (images, dataset_name)。

    images: [0,1] 区间的 float32 张量 [3, 224, 224] 列表。

    优先级:
    1. cifar100 (adaptation 本地 datasets/)
    2. cifar100 (项目级 datasets/, 只读)
    3. 合成随机图像 (固定种子, 250 张)
    """
    # 尝试加载 cifar100
    for dataset_dir in (LOCAL_DATASET_DIR, PROJECT_DATASET_DIR):
        cifar_path = dataset_dir / "cifar100"
        if cifar_path.exists():
            print(f"[benchmark] loading dataset from {cifar_path}")
            ds = load_from_disk(str(cifar_path))
            images = []
            for sample in ds:
                img = sample["img"] if "img" in sample else sample["image"]
                arr = np.asarray(img.convert("RGB"), dtype=np.float32) / 255.0  # [H, W, 3]
                t = torch.from_numpy(arr).permute(2, 0, 1).unsqueeze(0)  # [1, 3, H, W]
                t = F.interpolate(t, size=(224, 224), mode="bilinear", align_corners=False)
                images.append(t.squeeze(0))
            print(f"[benchmark] loaded {len(images)} images from cifar100")
            return images, "cifar100"

    # 降级到合成随机图像（固定种子，确定性）
    print("[benchmark] using generated random images (seed=42)")
    random.seed(42)
    np.random.seed(42)
    images = []
    for _ in range(250):
        arr = np.random.randint(0, 255, (224, 224, 3), dtype=np.uint8).astype(np.float32) / 255.0
        images.append(torch.from_numpy(arr).permute(2, 0, 1))  # [3, 224, 224]
    return images, "random"


def normalize_imagenet(x: torch.Tensor) -> torch.Tensor:
    """ImageNet 归一化，输入 [0,1] 区间张量。"""
    mean = torch.tensor(IMAGENET_MEAN, device=x.device, dtype=x.dtype).view(1, 3, 1, 1)
    std = torch.tensor(IMAGENET_STD, device=x.device, dtype=x.dtype).view(1, 3, 1, 1)
    return (x - mean) / std


def get_device(force_cpu: bool = False):
    """获取推理设备。若 force_cpu=True，强制返回 CPU。

    默认优先级: NPU > CUDA > CPU
    NPU 多卡时按 mem_get_info 自动选择空闲卡（本机严禁 ASCEND_RT_VISIBLE_DEVICES，
    一律用 torch.npu.set_device() 选卡）。
    """
    if force_cpu:
        return "cpu", 0, "cpu"

    try:
        import torch_npu  # noqa: F401

        if hasattr(torch, "npu") and torch.npu.is_available():
            count = torch.npu.device_count()
            best_index = 0
            best_free = -1
            for i in range(count):
                try:
                    free, total = torch.npu.mem_get_info(i)
                except Exception:
                    free, total = 0, 0
                print(f"[Device] NPU {i}: free={free / (1024**3):.1f} GB / total={total / (1024**3):.1f} GB")
                if free > best_free:
                    best_free = free
                    best_index = i
            torch.npu.set_device(best_index)
            device_name = torch.npu.get_device_name(best_index)
            print(f"[Device] Huawei Ascend NPU detected; selected idle device npu:{best_index} ({device_name})")
            return f"npu:{best_index}", count, device_name
    except ImportError:
        pass
    if torch.cuda.is_available():
        device_name = torch.cuda.get_device_name(0)
        return "cuda:0", torch.cuda.device_count(), device_name
    return "cpu", 0, "cpu"


class _PerfMonitor:
    """性能监控器：测量推理延迟和峰值内存"""

    def __init__(self, device_type, device_ids=None):
        self.device_type = device_type
        self.device_ids = device_ids
        self.start = None
        self.latency_s = None
        self.peak_memory_mb = None

    def __enter__(self):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401

            torch.npu.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.npu.reset_peak_memory_stats(dev_id)
            else:
                torch.npu.reset_peak_memory_stats()
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.cuda.reset_peak_memory_stats(dev_id)
            else:
                torch.cuda.reset_peak_memory_stats()

        self.start = time.perf_counter()
        return self

    def __exit__(self, *args):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401

            torch.npu.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.npu.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.npu.max_memory_allocated() / (1024**2)
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.cuda.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.cuda.max_memory_allocated() / (1024**2)
        else:
            self.peak_memory_mb = 0.0

        self.latency_s = time.perf_counter() - self.start
        return False


def get_profiler_context(device_short):
    """根据硬件动态返回原生 Profiler 上下文"""
    if device_short == "npu":
        import torch_npu  # noqa: F401
        from torch_npu.profiler import ProfilerActivity as NPUActivity
        from torch_npu.profiler import profile as npu_profile

        activities = [NPUActivity.CPU, NPUActivity.NPU]
        return npu_profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)
    else:
        activities = [torch.profiler.ProfilerActivity.CPU]
        if device_short == "cuda":
            activities.append(torch.profiler.ProfilerActivity.CUDA)

        return torch.profiler.profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)


def get_dtype_str(dtype: torch.dtype) -> str:
    """Convert torch dtype to short string (fp32, fp16, bf16)."""
    dtype_map = {
        torch.float32: "fp32",
        torch.float16: "fp16",
        torch.bfloat16: "bf16",
        torch.int64: "int64",
        torch.int32: "int32",
    }
    return dtype_map.get(dtype, str(dtype).replace("torch.", ""))


def get_package_versions() -> dict:
    """获取关键依赖包的版本"""
    import importlib.metadata

    packages = ["torch", "timm", "torch_npu", "numpy", "datasets", "torchvision"]
    versions = {}
    for pkg in packages:
        try:
            versions[pkg] = importlib.metadata.version(pkg)
        except importlib.metadata.PackageNotFoundError:
            versions[pkg] = "not_installed"
    return versions


def from_pretrained(device):
    """Tier2: 加载 timm hf-hub 预训练权重（下载失败直接抛错终止，禁止静默降级）。"""
    model = timm.create_model(f"hf-hub:{MODEL_ID}", pretrained=True, num_classes=NUM_CLASSES)
    model = model.to(device)
    return model


def from_config(device):
    """Tier1: 随机权重（timm create_model, pretrained=False）。"""
    model = timm.create_model(ARCH, pretrained=False, num_classes=NUM_CLASSES)
    model = model.to(device)
    return model


def setup_model(use_pretrained: bool, device):
    """加载模型 (timm vision classification)，按 use_pretrained 分支 Tier1/Tier2。"""
    if use_pretrained:
        model = from_pretrained(device)
    else:
        model = from_config(device)
    model.eval()
    return model


def run_step1(model, first_device, device_short, device_ids, mode_str, adapt_dir: Path, dataset_name: str, images: list[torch.Tensor]):
    """Step 1: 单样本推理 -> trace_*.json + benchmark_metrics_*.json (Vision)"""
    print("\n" + "=" * 60)
    print("Step 1: 单样本推理 (性能分析)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    trace_path = adapt_dir / f"trace_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"
    metrics_path = adapt_dir / f"benchmark_metrics_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"

    # 单样本（空数据集时使用 fallback）
    image = images[0] if images else torch.rand(*INPUT_SIZE)
    x = normalize_imagenet(image.unsqueeze(0)).to(first_device)

    profiler_context = get_profiler_context(device_short)

    start_time = datetime.now().isoformat()
    with profiler_context as prof:
        with _PerfMonitor(device_short, device_ids) as m:
            with torch.no_grad():
                logits = model(x)
                assert logits.dim() == 2 and torch.isfinite(logits).all(), "invalid logits"

        latency_s = m.latency_s
        peak_memory_mb = m.peak_memory_mb

    # 导出 trace
    prof.export_chrome_trace(str(trace_path))

    # 获取实际设备型号
    device_model = "unknown"
    if device_short == "npu" and first_device.index is not None:
        device_model = torch.npu.get_device_name(first_device.index)
    elif device_short == "cuda" and first_device.index is not None:
        device_model = torch.cuda.get_device_name(first_device.index)

    # 写入 metrics（end_time 将在 main() 末尾更新）
    metrics = {
        "start_time": start_time,
        "latency_s": round(latency_s, 6),
        "step1_forward_latency_s": round(latency_s, 6),
        "peak_memory_mb": round(peak_memory_mb, 2),
        "num_samples": len(images),
        "device": str(first_device),
        "device_model": device_model,
        "mode": mode_str,
        "dataset": dataset_name,
        "dtype": dtype_str,
        "output_type": "class_labels",
        "packages": get_package_versions(),
    }
    metrics_path.write_text(json.dumps(metrics, indent=2))

    # 清理临时目录（忽略错误，NPU profiler 可能留下文件）
    prof_dir = adapt_dir / "export_only_prof_dir"
    if prof_dir.exists():
        shutil.rmtree(prof_dir, ignore_errors=True)
        print(f"[benchmark] cleaned up {prof_dir}")

    print(f"[benchmark] trace saved to {trace_path}")
    print(f"[benchmark] metrics saved to {metrics_path}")
    print(f"[benchmark] {metrics}")

    return trace_path, metrics_path, start_time


def run_step2(model, first_device, device_short, mode_str, adapt_dir: Path, dataset_name: str, images: list[torch.Tensor], max_samples: int = 250):
    """Step 2: 全样本推理 -> outputs_*.pt + top-1/top-5 logits 画像 (Vision, 非生成式)

    Vision 模型不测量 TTFT/TPOT，返回 None。

    输出格式 (outputs_*.pt, dict):
    - class_labels: top-1 类别标签字符串列表（ImageNet 类索引）
    - top5_ids: 每样本 top-5 类别索引
    - top5_scores: 每样本 top-5 logits 值

    Returns:
        tuple: (outputs_path, None, None, avg_sample_s, profile_stats)
    """
    print("\n" + "=" * 60)
    print("Step 2: 全样本推理 (精度测试 + top-1/top-5 logits 画像)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    outputs_path = adapt_dir / f"outputs_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.pt"

    # 限制样本数（R1 规则：最多 250 个样本）
    images = images[:max_samples]
    print(f"[benchmark] {len(images)} images to process (max {max_samples})")

    all_labels = []
    all_top5_ids = []
    all_top5_scores = []

    step2_start = time.perf_counter()
    with torch.no_grad():
        for i, image in enumerate(images):
            x = normalize_imagenet(image.unsqueeze(0)).to(first_device)
            logits = model(x)  # [1, NUM_CLASSES]

            top5_vals, top5_ids = torch.topk(logits[0], k=5)
            top1_id = int(top5_ids[0].item())
            all_labels.append(str(top1_id))
            all_top5_ids.append([int(v) for v in top5_ids.cpu().tolist()])
            all_top5_scores.append([float(v) for v in top5_vals.cpu().tolist()])

            del logits, top5_vals, top5_ids, x

            if (i + 1) % 32 == 0:
                if device_short == "npu":
                    torch.npu.empty_cache()
                elif device_short == "cuda":
                    torch.cuda.empty_cache()
                print(f"[benchmark] processed {i + 1}/{len(images)} images (cache cleared)")
            elif (i + 1) % 8 == 0:
                print(f"[benchmark] processed {i + 1}/{len(images)} images")

    step2_elapsed = time.perf_counter() - step2_start
    avg_sample_s = step2_elapsed / len(images) if images else None

    # 保存 outputs（class_labels + top-1/top-5 logits 画像）
    output_data = {
        "class_labels": all_labels,
        "top5_ids": all_top5_ids,
        "top5_scores": all_top5_scores,
    }
    torch.save(output_data, outputs_path)

    # top-1/top-5 logits 画像统计
    top1_scores = [s[0] for s in all_top5_scores]
    top5_spread = [s[0] - s[-1] for s in all_top5_scores]
    unique_top1 = len(set(all_labels))
    profile_stats = {
        "top1_logit_avg": round(sum(top1_scores) / len(top1_scores), 4),
        "top1_logit_min": round(min(top1_scores), 4),
        "top1_logit_max": round(max(top1_scores), 4),
        "top5_spread_avg": round(sum(top5_spread) / len(top5_spread), 4),
        "unique_top1_classes": unique_top1,
    }

    print(f"[benchmark] outputs saved to {outputs_path}")
    print(f"[benchmark]   - class_labels: {len(all_labels)} samples (unique top-1 classes: {unique_top1})")
    print(f"[benchmark]   - top-1 logit avg/min/max: {profile_stats['top1_logit_avg']}/{profile_stats['top1_logit_min']}/{profile_stats['top1_logit_max']}")
    print(f"[benchmark]   - top-5 spread avg: {profile_stats['top5_spread_avg']}")
    print(f"[benchmark] avg per-sample forward time: {avg_sample_s:.6f} s")

    return outputs_path, None, None, avg_sample_s, profile_stats


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--use-pretrained", action="store_true", help="Tier2: load pretrained weights")
    parser.add_argument("--max-samples", type=int, default=250, help="Max samples to process (default 250, per R1 rule)")
    parser.add_argument("--cpu", action="store_true", help="Force CPU inference (disable NPU/CUDA)")
    args = parser.parse_args()

    adapt_dir = Path(__file__).resolve().parent

    # 1. Seed
    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    device, _, _ = get_device(force_cpu=args.cpu)
    if device.startswith("npu"):
        torch.npu.manual_seed_all(SEED)
    elif device.startswith("cuda"):
        torch.cuda.manual_seed_all(SEED)

    # 开启全局确定性算法（确保 CUDA/NPU 输出一致）
    torch.use_deterministic_algorithms(True, warn_only=True)

    # 仅在非 --cpu 模式下检查设备
    if not args.cpu:
        assert device.startswith(("npu", "cuda")), f"Need NPU or CUDA, got {device}"

    # 2. Load dataset（提前截断，保证 metrics.num_samples 与实际处理样本数一致）
    images, dataset_name = load_benchmark_images()
    images = images[: args.max_samples]
    print(f"[benchmark] using dataset: {dataset_name}, images for this run: {len(images)}, max_samples: {args.max_samples}")

    # 3. Model
    model = setup_model(args.use_pretrained, device)

    first_device = next(model.parameters()).device
    device_short = first_device.type
    mode_str = "pretrained" if args.use_pretrained else "config"
    n_params = sum(p.numel() for p in model.parameters()) / 1e6
    print(f"[benchmark] model: {ARCH}, params: {n_params:.2f}M, mode: {mode_str}, device: {first_device}")

    # 提取设备 IDs
    device_ids = [first_device.index] if first_device.index is not None else None

    # Step 1: 单样本 -> trace + metrics
    trace_path, metrics_path, start_time = run_step1(model, first_device, device_short, device_ids, mode_str, adapt_dir, dataset_name, images)

    # Step 2: 全样本 -> outputs + top-1/top-5 画像 (Vision 不测量 TTFT/TPOT)
    outputs_path, ttft_avg, tpot_avg, avg_sample_s, profile_stats = run_step2(model, first_device, device_short, mode_str, adapt_dir, dataset_name, images, args.max_samples)

    # 更新 metrics 文件（end_time + ttft/tpot=null + latency_s 用 Step2 每样本均值覆盖）
    end_time = datetime.now().isoformat()
    with open(metrics_path, "r") as f:
        metrics = json.load(f)

    metrics["end_time"] = end_time
    metrics["ttft_ms"] = ttft_avg  # Vision 非生成式：null
    metrics["tpot_ms"] = tpot_avg  # Vision 非生成式：null
    if avg_sample_s is not None:
        metrics["latency_s"] = round(max(float(metrics.get("latency_s", 0.0)), float(avg_sample_s)), 6)
    metrics["top1_top5_profile"] = profile_stats

    with open(metrics_path, "w") as f:
        json.dump(metrics, indent=2, fp=f)

    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"  ✅ trace: {trace_path}")
    print(f"  ✅ metrics: {metrics_path}")
    print(f"  ✅ outputs: {outputs_path} (含 class_labels + top5_ids + top5_scores)")
    print(f"  📊 top-1/top-5 profile: {profile_stats}")

    print(f"\n💡 To analyze NPU fallback, run:")
    print(f"   uv run python benchmark/scripts/benchmark_tool.py trace {trace_path.name}")
    print(f"   (add -v for detailed report, -j for JSON)")


if __name__ == "__main__":
    main()
