"""
Benchmark accuracy_run.py for openai-community/gpt2.
Generated by benchmark-runner. Dimension 2 (accuracy .pt) + 3 (perf) + 4 (trace, required).

Teacher-forcing 合同：单步前向获取 last_token_logits + perplexity，不做自回归生成。
Step 1: 单样本 -> trace_*.json + benchmark_metrics_*.json (性能分析)
Step 2: 全样本 -> outputs_*.pt (精度测试)

Usage:
    uv run python accuracy_run.py                    # 完整执行 (step1 -> step2)
    uv run python accuracy_run.py --use-pretrained   # Tier2: 加载预训练权重
    uv run python accuracy_run.py --cpu              # 强制 CPU 推理 (禁用 NPU/CUDA)

Model Type: causal_lm
Recommended Dataset: wikitext
"""

import argparse
import json
import os
import random
import shutil
import time
from datetime import datetime
from pathlib import Path

# 国内网络环境默认走 HF 镜像（外部已设置的环境变量优先）
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")
os.environ.setdefault("HF_HUB_DISABLE_XET", "1")

import numpy as np
import torch
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer
from transformers import set_seed as transformers_set_seed

from datasets import load_from_disk

# 数据集配置
DATASET_DIR = Path(__file__).resolve().parent.parent.parent / "datasets"
DATASET_TEXT_FIELD = "article"  # cnn_dailymail 的文本字段
def load_benchmark_texts() -> tuple[list[str], str]:
    """加载测试数据集文本，返回 (texts, dataset_name)。

    优先级:
    - token_classification: 1. conll2003 2. wikitext 3. 内置
    - 其他: 1. wikitext 2. cnn_dailymail 3. imdb 4. 内置
    """
    # 尝试加载 wikitext
    wikitext_path = DATASET_DIR / "wikitext___wikitext-2-raw-v1"
    if wikitext_path.exists():
        print(f"[benchmark] loading dataset from {wikitext_path}")
        ds = load_from_disk(str(wikitext_path))
        texts = sorted([sample["text"] for sample in ds if sample.get("text", "").strip()])
        print(f"[benchmark] loaded {len(texts)} samples from wikitext")
        return texts, "wikitext"

    # 尝试加载 cnn_dailymail
    cnn_path = DATASET_DIR / "cnn_dailymail___3.0.0"
    if cnn_path.exists():
        print(f"[benchmark] loading dataset from {cnn_path}")
        ds = load_from_disk(str(cnn_path))
        texts = sorted([sample[DATASET_TEXT_FIELD] for sample in ds if sample[DATASET_TEXT_FIELD].strip()])
        print(f"[benchmark] loaded {len(texts)} samples from cnn_dailymail")
        return texts, "cnn_dailymail"

    # 尝试加载 imdb
    imdb_path = DATASET_DIR / "imdb"
    if imdb_path.exists():
        print(f"[benchmark] loading dataset from {imdb_path}")
        ds = load_from_disk(str(imdb_path))
        texts = sorted([sample["text"] for sample in ds if sample["text"].strip()])
        print(f"[benchmark] loaded {len(texts)} samples from imdb")
        return texts, "imdb"

    # 降级到内置文本（55 条，满足 completed gate 的 num_samples >= 50 要求）
    print("[benchmark] using built-in benchmark texts")
    builtin_texts = [
        "Hello, this is a benchmark run.",
        "The quick brown fox jumps over the lazy dog.",
        "Machine learning is a subset of artificial intelligence.",
        "Natural language processing enables computers to understand human language.",
        "Transformers have revolutionized the field of deep learning.",
        "PyTorch is an open-source machine learning framework.",
        "The attention mechanism allows models to focus on relevant parts of input.",
        "Language models can generate coherent and contextually relevant text.",
        "Artificial neural networks are inspired by the structure of the human brain.",
        "Deep learning models require large amounts of data to achieve good performance.",
        "Convolutional neural networks are commonly used for image classification tasks.",
        "Recurrent neural networks are designed to process sequential data such as text.",
        "Gradient descent is an optimization algorithm used to minimize the loss function.",
        "Backpropagation computes the gradients needed to update the network weights.",
        "Transfer learning allows a model pretrained on one task to be reused on another.",
        "Fine-tuning adjusts the weights of a pretrained model on a smaller dataset.",
        "Tokenization splits raw text into smaller units that a model can process.",
        "The vocabulary of a language model defines the set of tokens it can recognize.",
        "Perplexity measures how well a probability model predicts a sample of text.",
        "A lower perplexity indicates that the model is more confident in its predictions.",
        "Inference latency is the time required for a model to produce an output.",
        "Throughput describes how many samples a system can process per unit of time.",
        "Quantization reduces the numerical precision of model weights to save memory.",
        "Model compression techniques aim to make neural networks smaller and faster.",
        "Knowledge distillation trains a small student model to mimic a larger teacher.",
        "Data augmentation increases the diversity of training data with modified samples.",
        "Regularization methods such as dropout help prevent overfitting during training.",
        "Batch normalization stabilizes and accelerates the training of deep networks.",
        "Learning rate schedules adjust the step size during the course of training.",
        "Early stopping halts training when validation performance stops improving.",
        "Cross-validation provides a robust estimate of model performance on new data.",
        "Precision and recall are complementary metrics for evaluating classification models.",
        "The F1 score combines precision and recall into a single harmonic mean value.",
        "Confusion matrices summarize the correct and incorrect predictions of a classifier.",
        "Benchmark suites provide standardized tasks for comparing different models.",
        "Reproducibility requires fixing random seeds and recording the software environment.",
        "Deterministic algorithms produce identical outputs for identical inputs.",
        "Graphics processing units accelerate the matrix operations used in deep learning.",
        "Ascend neural processing units provide high-performance computing for AI workloads.",
        "Hardware accelerators can significantly reduce the time needed to train models.",
        "Distributed training splits a workload across multiple devices to scale up.",
        "Mixed precision training uses both float16 and float32 for efficiency.",
        "The softmax function converts logits into a probability distribution.",
        "Cross-entropy loss is widely used for training classification models.",
        "Word embeddings represent words as dense vectors in a continuous space.",
        "Contextual embeddings produce different representations depending on surrounding words.",
        "Self-attention computes weighted combinations of all positions in a sequence.",
        "Positional encodings inject information about token order into transformers.",
        "Encoder-decoder architectures are common in machine translation systems.",
        "Autoregressive models generate text one token at a time from left to right.",
        "Greedy decoding always selects the most probable next token.",
        "Beam search explores multiple candidate sequences to improve generation quality.",
        "Sampling strategies such as top-k and top-p control the diversity of generation.",
        "Evaluating generated text remains a challenging open problem in the field.",
        "Well-designed benchmarks help track progress across model generations.",
    ]
    return builtin_texts, "builtin"


def select_idle_npu() -> int:
    """选择空闲 HBM 最多的 NPU 并设为当前设备。

    本机禁止设置 ASCEND_RT_VISIBLE_DEVICES（会导致 aclInit error 107001），
    因此通过 torch.npu.set_device() 在多卡中选定单卡（多 runner 并发，务必选空闲卡）。
    """
    count = torch.npu.device_count()
    best_idx, best_free = 0, -1
    for i in range(count):
        try:
            free, _total = torch.npu.mem_get_info(i)
        except Exception:
            free = 0
        print(f"[Device] NPU {i}: free HBM {free / 1024**3:.1f} GiB")
        if free > best_free:
            best_idx, best_free = i, free
    torch.npu.set_device(best_idx)
    return best_idx


def get_device(force_cpu: bool = False):
    """获取推理设备。若 force_cpu=True，强制返回 CPU。

    默认优先级: NPU > CUDA > CPU。
    NPU 场景下动态选择空闲卡（本机多 agent 并发，严禁默认 0 号卡）。
    """
    if force_cpu:
        return "cpu", 0, "cpu"

    try:
        import torch_npu  # noqa: F401

        if hasattr(torch, "npu") and torch.npu.is_available():
            idx = select_idle_npu()
            device_name = torch.npu.get_device_name(idx) if torch.npu.device_count() > 0 else "unknown"
            return f"npu:{idx}", torch.npu.device_count(), device_name
    except ImportError:
        pass
    if torch.cuda.is_available():
        device_name = torch.cuda.get_device_name(0)
        return "cuda:0", torch.cuda.device_count(), device_name
    return "cpu", 0, "cpu"


class _PerfMonitor:
    """性能监控器：测量推理延迟和峰值内存"""

    def __init__(self, device_type, device_ids=None):
        self.device_type = device_type
        self.device_ids = device_ids
        self.start = None
        self.latency_s = None
        self.peak_memory_mb = None

    def __enter__(self):
        if self.device_type == "npu":
            import torch_npu

            torch.npu.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.npu.reset_peak_memory_stats(dev_id)
            else:
                torch.npu.reset_peak_memory_stats()
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.cuda.reset_peak_memory_stats(dev_id)
            else:
                torch.cuda.reset_peak_memory_stats()

        self.start = time.perf_counter()
        return self

    def __exit__(self, *args):
        if self.device_type == "npu":
            import torch_npu

            torch.npu.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.npu.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.npu.max_memory_allocated() / (1024**2)
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.cuda.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.cuda.max_memory_allocated() / (1024**2)
        else:
            self.peak_memory_mb = 0.0

        self.latency_s = time.perf_counter() - self.start
        return False


def get_profiler_context(device_short):
    """根据硬件动态返回原生 Profiler 上下文"""
    if device_short == "npu":
        import torch_npu
        from torch_npu.profiler import ProfilerActivity as NPUActivity
        from torch_npu.profiler import profile as npu_profile

        activities = [NPUActivity.CPU, NPUActivity.NPU]
        return npu_profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)
    else:
        activities = [torch.profiler.ProfilerActivity.CPU]
        if device_short == "cuda":
            activities.append(torch.profiler.ProfilerActivity.CUDA)

        return torch.profiler.profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)


def get_dtype_str(dtype: torch.dtype) -> str:
    """Convert torch dtype to short string (fp32, fp16, bf16)."""
    dtype_map = {
        torch.float32: "fp32",
        torch.float16: "fp16",
        torch.bfloat16: "bf16",
        torch.int64: "int64",
        torch.int32: "int32",
    }
    return dtype_map.get(dtype, str(dtype).replace("torch.", ""))


def get_package_versions() -> dict:
    """获取关键依赖包的版本"""
    import importlib.metadata
    packages = ["torch", "transformers", "torch_npu", "numpy", "datasets"]
    versions = {}
    for pkg in packages:
        try:
            versions[pkg] = importlib.metadata.version(pkg)
        except importlib.metadata.PackageNotFoundError:
            versions[pkg] = "not_installed"
    return versions
def setup_model(use_pretrained: bool, device, cache_dir: str):
    """加载模型 (CausalLM)"""
    MODEL_ID = "openai-community/gpt2"

    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True, cache_dir=cache_dir)
    config = AutoConfig.from_pretrained(MODEL_ID, trust_remote_code=True, cache_dir=cache_dir)

    if use_pretrained:
        # 本机多 runner 并发，禁用 device_map="auto"（可能跨卡映射），
        # gpt2 仅 124M 参数，直接整体放到选定的单卡上
        model = AutoModelForCausalLM.from_pretrained(MODEL_ID, trust_remote_code=True, torch_dtype="auto", cache_dir=cache_dir)
        model = model.to(device)
    else:
        model = AutoModelForCausalLM.from_config(config, trust_remote_code=True)
        model = model.to(device)
    model.eval()

    return model, tokenizer
def run_step1(model, tokenizer, first_device, device_short, device_ids, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str]):
    """Step 1: 单样本推理 -> trace_*.json + benchmark_metrics_*.json"""
    print("\n" + "=" * 60)
    print("Step 1: 单样本推理 (性能分析)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    trace_path = adapt_dir / f"trace_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"
    metrics_path = adapt_dir / f"benchmark_metrics_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"

    # 单样本（空数据集时使用 fallback）
    text = texts[0] if texts else "Hello, benchmark."
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(first_device)

    profiler_context = get_profiler_context(device_short)

    start_time = datetime.now().isoformat()
    with profiler_context as prof:
        with _PerfMonitor(device_short, device_ids) as m:
            with torch.no_grad():
                out = model(**inputs)
                _ = out.logits if hasattr(out, "logits") else out[0]  # 仅推理，不保存

        latency_s = m.latency_s
        peak_memory_mb = m.peak_memory_mb

    # 导出 trace
    prof.export_chrome_trace(str(trace_path))

    # 获取实际设备型号
    device_model = "unknown"
    if device_short == "npu" and first_device.index is not None:
        device_model = torch.npu.get_device_name(first_device.index)
    elif device_short == "cuda" and first_device.index is not None:
        device_model = torch.cuda.get_device_name(first_device.index)

    # 写入 metrics（end_time / ttft_ms / tpot_ms / 最终 latency_s 将在 main() 末尾更新）
    # 注意：此处的 latency_s 是 Step1 单样本 forward 延迟（诊断用），
    # main() 末尾会用 Step2 全样本平均推理延迟覆盖，保证与 ttft_ms 口径一致。
    metrics = {
        "start_time": start_time,
        "latency_s": round(latency_s, 6),
        "step1_forward_latency_s": round(latency_s, 6),
        "peak_memory_mb": round(peak_memory_mb, 2),
        "num_samples": len(texts),
        "device": str(first_device),
        "device_model": device_model,
        "mode": mode_str,
        "dataset": dataset_name,
        "dtype": dtype_str,
        "output_type": "logits",
        "packages": get_package_versions(),
    }
    metrics_path.write_text(json.dumps(metrics, indent=2))

    # 清理临时目录（忽略错误，NPU profiler 可能留下文件）
    prof_dir = adapt_dir / "export_only_prof_dir"
    if prof_dir.exists():
        shutil.rmtree(prof_dir, ignore_errors=True)
        print(f"[benchmark] cleaned up {prof_dir}")

    print(f"[benchmark] trace saved to {trace_path}")
    print(f"[benchmark] metrics saved to {metrics_path}")
    print(f"[benchmark] {metrics}")

    return trace_path, metrics_path, start_time
def run_step2(model, tokenizer, first_device, device_short, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str], max_samples: int = 250):
    """Step 2: 全样本 teacher-forcing 前向 -> outputs_*.pt (logits + perplexity)

    Teacher-forcing 合同：对每个样本做单步前向，捕获 last_token_logits 和 perplexity。
    不做自回归生成，仅用于算子精度验证和推理延迟测量。

    内存优化：
    - 每个样本处理完后立即清理
    - 每 32 个样本清理 NPU/CUDA 缓存
    - 默认限制样本数为 250（避免产出文件过大）

    输出格式 (outputs_*.pt):
    - logits: 每个 prompt 最后一个 token 的 logits 张量列表
    - perplexity: 每个样本的 perplexity 值列表

    Returns:
        tuple: (outputs_path, avg_latency_s)
    """
    print("\n" + "=" * 60)
    print("Step 2: 全样本 teacher-forcing 前向 (logits + PPL)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    outputs_path = adapt_dir / f"outputs_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.pt"

    # 限制样本数（R1 规则：最多 250 个样本）
    texts = texts[:max_samples]
    print(f"[benchmark] {len(texts)} samples to process (max {max_samples})")

    all_logits = []  # 保存 logits
    all_ppl = []  # 保存 perplexity
    all_sample_latency = []  # 每样本前向延迟

    # warmup: 3 次前向预热（不计入计时）
    warmup_iterations = 3
    print(f"[benchmark] warmup {warmup_iterations} iterations...")
    warmup_text = texts[0] if texts else "Hello, benchmark."
    warmup_inputs = tokenizer(warmup_text, return_tensors="pt", truncation=True, max_length=512).to(first_device)
    with torch.no_grad():
        for _ in range(warmup_iterations):
            _ = model(**warmup_inputs)
    if device_short == "npu":
        torch.npu.synchronize()
    elif device_short == "cuda":
        torch.cuda.synchronize()
    print(f"[benchmark] warmup done")

    step2_start = time.perf_counter()

    with torch.no_grad():
        for i, text in enumerate(texts):
            sample_start = time.perf_counter()
            inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(first_device)

            # 前向推理获取 logits（teacher-forcing，单步前向）
            logits_output = model(**inputs)
            last_token_logits = logits_output.logits[0, -1, :].cpu()  # [vocab_size]
            all_logits.append(last_token_logits)

            # 计算 perplexity
            # PPL = exp(cross_entropy_loss)
            # labels = input_ids shifted by 1
            labels = inputs["input_ids"]
            logits = logits_output.logits  # [1, seq_len, vocab_size]
            shift_logits = logits[..., :-1, :].contiguous()
            shift_labels = labels[..., 1:].contiguous()
            loss_fct = torch.nn.CrossEntropyLoss(reduction="mean")
            loss = loss_fct(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))
            ppl = torch.exp(loss).item()
            all_ppl.append(ppl)

            all_sample_latency.append(time.perf_counter() - sample_start)

            del inputs, logits_output

            # 每 32 个样本清理缓存（更频繁以避免 OOM）
            if (i + 1) % 32 == 0:
                if device_short == "npu":
                    torch.npu.empty_cache()
                elif device_short == "cuda":
                    torch.cuda.empty_cache()
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples (cache cleared)")

            elif (i + 1) % 8 == 0:
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples")

    step2_end = time.perf_counter()
    wall_clock_s = round(step2_end - step2_start, 6)

    # 保存 outputs（包含 logits 和 perplexity）
    output_data = {
        "logits": all_logits,
        "perplexity": all_ppl,
    }
    torch.save(output_data, outputs_path)

    # 计算 PPL 统计
    ppl_avg = round(sum(all_ppl) / len(all_ppl), 2) if all_ppl else None

    # 计算全样本平均推理延迟（每样本前向）
    avg_latency_s = round(sum(all_sample_latency) / len(all_sample_latency), 6) if all_sample_latency else None

    print(f"[benchmark] outputs saved to {outputs_path}")
    print(f"[benchmark]   - logits: {len(all_logits)} samples, shape: {all_logits[0].shape}")
    print(f"[benchmark]   - perplexity: avg={ppl_avg}, min={min(all_ppl):.2f}, max={max(all_ppl):.2f}")
    print(f"[benchmark] wall_clock_s: {wall_clock_s}")
    print(f"[benchmark] avg per-sample latency: {avg_latency_s} s")

    return outputs_path, avg_latency_s, wall_clock_s, warmup_iterations


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--use-pretrained", action="store_true", help="Tier2: load pretrained weights")
    parser.add_argument("--max-samples", type=int, default=250, help="Max samples to process (default 250, per R1 rule)")
    parser.add_argument("--cpu", action="store_true", help="Force CPU inference (disable NPU/CUDA)")
    args = parser.parse_args()

    MODEL_ID = "openai-community/gpt2"
    CACHE_DIR = (Path(__file__).resolve().parent / "models").as_posix()
    ADAPT_DIR = Path(__file__).resolve().parent

    # 1. Seed
    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    transformers_set_seed(SEED)
    device, _, _ = get_device(force_cpu=args.cpu)
    if device.startswith("npu"):
        torch.npu.manual_seed_all(SEED)
    elif device.startswith("cuda"):
        torch.cuda.manual_seed_all(SEED)

    # 开启全局确定性算法（确保 CUDA/NPU 输出一致）
    torch.use_deterministic_algorithms(True, warn_only=True)

    # 仅在非 --cpu 模式下检查设备
    if not args.cpu:
        assert device.startswith(("npu", "cuda")), f"Need NPU or CUDA, got {device}"
    # 2. Load dataset（在入口处按 max_samples 截断，保证 metrics.num_samples 与实际处理数一致）
    texts, dataset_name = load_benchmark_texts()
    texts = texts[: args.max_samples]
    print(f"[benchmark] using dataset: {dataset_name}, total samples: {len(texts)}, max_samples: {args.max_samples}")

    # 3. Model
    model, processor = setup_model(args.use_pretrained, device, CACHE_DIR)

    first_device = next(model.parameters()).device
    device_short = first_device.type
    mode_str = "pretrained" if args.use_pretrained else "config"

    # 提取设备 IDs
    device_ids = None
    if hasattr(model, "hf_device_map"):
        device_ids = list(set(dev.index if hasattr(dev, "index") else dev for dev in model.hf_device_map.values()))
    elif first_device.index is not None:
        device_ids = [first_device.index]

    # Step 1: 单样本 -> trace + metrics
    trace_path, metrics_path, start_time = run_step1(model, processor, first_device, device_short, device_ids, mode_str, ADAPT_DIR, dataset_name, texts)

    # Step 2: 全样本 -> outputs + logits + PPL
    outputs_path, avg_latency_s, wall_clock_s, warmup_iterations = run_step2(model, processor, first_device, device_short, mode_str, ADAPT_DIR, dataset_name, texts, args.max_samples)

    # 更新 metrics 文件（添加 end_time, wall_clock_s；用 Step2 全样本平均延迟覆盖 latency_s）
    end_time = datetime.now().isoformat()
    with open(metrics_path, "r") as f:
        metrics = json.load(f)

    metrics["end_time"] = end_time
    metrics["wall_clock_s"] = wall_clock_s
    metrics["warmup_iterations"] = warmup_iterations
    if avg_latency_s is not None:
        metrics["latency_s"] = avg_latency_s

    with open(metrics_path, "w") as f:
        json.dump(metrics, indent=2, fp=f)

    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"  ✅ trace: {trace_path}")
    print(f"  ✅ metrics: {metrics_path}")
    print(f"  ✅ outputs: {outputs_path} (含 logits + perplexity)")
    print(f"  📊 wall_clock_s: {wall_clock_s}, avg latency: {avg_latency_s} s")

    print(f"\n💡 To analyze NPU fallback, run:")
    print(f"   uv run python benchmark/scripts/benchmark_tool.py trace {trace_path.name}")
    print(f"   (add -v for detailed report, -j for JSON)")
    print(f"\n💡 To compare CUDA/NPU outputs (including logits):")
    print(f"   python benchmark/scripts/benchmark_tool.py compare --adaptation openai_community_gpt2")


if __name__ == "__main__":
    main()
