"""
Benchmark accuracy_run.py for google-bert/bert-base-uncased (Masked LM).
Generated by benchmark-runner. Dimension 2 (accuracy .pt) + 3 (perf) + 4 (trace, required).

两步依次执行:
  Step 1: 单样本 -> trace_*.json + benchmark_metrics_*.json (性能分析)
  Step 2: 全样本 -> outputs_*.pt (精度测试)

MLM (非生成式) 画像方式: [MASK] 填空 + 伪困惑度 (pseudo-perplexity)
  - 对每条文本确定性地随机掩盖 ~15% 的非特殊 token (固定种子，可复现)
  - forward 后在 [MASK] 位置取 argmax 预测原词并还原句子 (填空画像)
  - 在 [MASK] 位置对原始 token 计算交叉熵 -> exp(loss) 即伪困惑度
  - 同时保存首个 [MASK] 位置的完整 logits (用于 CUDA/NPU 算子精度对比)

Usage:
    uv run python accuracy_run.py                    # 完整执行 (step1 -> step2, config 随机权重)
    uv run python accuracy_run.py --use-pretrained   # Tier2: 加载预训练权重
    uv run python accuracy_run.py --cpu              # 强制 CPU 推理 (禁用 NPU/CUDA)

Model Type: masked_lm (encoder, non-generative)
Recommended Dataset: wikitext (缺失时降级内置文本)

Host notes (2x Ascend910, 多 runner 并发):
- 本机严禁设置 ASCEND_RT_VISIBLE_DEVICES（会导致 aclInit error 107001）；
  选卡一律通过 torch.npu.mem_get_info() 挑空闲卡 + torch.npu.set_device()。
"""

import argparse
import json
import os
import random
import shutil
import time
from datetime import datetime
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F

# HuggingFace 镜像（国内直连 huggingface.co 不通）
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")
os.environ.setdefault("HF_HUB_DISABLE_XET", "1")

from transformers import AutoConfig, AutoModelForMaskedLM, AutoTokenizer  # noqa: E402
from transformers import set_seed as transformers_set_seed  # noqa: E402

from datasets import load_from_disk  # noqa: E402

# 数据集配置
DATASET_DIR = Path(__file__).resolve().parent.parent.parent / "datasets"
DATASET_TEXT_FIELD = "article"  # cnn_dailymail 的文本字段
MASK_RATIO = 0.15  # MLM 掩盖比例
MASK_SEED_BASE = 42  # 每样本掩盖位置的确定性种子基数


def load_benchmark_texts() -> tuple[list[str], str]:
    """加载测试数据集文本，返回 (texts, dataset_name)。

    优先级: 1. wikitext 2. cnn_dailymail 3. imdb 4. 内置
    """
    # 尝试加载 wikitext
    wikitext_path = DATASET_DIR / "wikitext___wikitext-2-raw-v1"
    if wikitext_path.exists():
        print(f"[benchmark] loading dataset from {wikitext_path}")
        ds = load_from_disk(str(wikitext_path))
        texts = sorted([sample["text"] for sample in ds if sample.get("text", "").strip()])
        print(f"[benchmark] loaded {len(texts)} samples from wikitext")
        return texts, "wikitext"

    # 尝试加载 cnn_dailymail
    cnn_path = DATASET_DIR / "cnn_dailymail___3.0.0"
    if cnn_path.exists():
        print(f"[benchmark] loading dataset from {cnn_path}")
        ds = load_from_disk(str(cnn_path))
        texts = sorted([sample[DATASET_TEXT_FIELD] for sample in ds if sample[DATASET_TEXT_FIELD].strip()])
        print(f"[benchmark] loaded {len(texts)} samples from cnn_dailymail")
        return texts, "cnn_dailymail"

    # 尝试加载 imdb
    imdb_path = DATASET_DIR / "imdb"
    if imdb_path.exists():
        print(f"[benchmark] loading dataset from {imdb_path}")
        ds = load_from_disk(str(imdb_path))
        texts = sorted([sample["text"] for sample in ds if sample["text"].strip()])
        print(f"[benchmark] loaded {len(texts)} samples from imdb")
        return texts, "imdb"

    # 降级到内置文本（64 条，保证 num_samples >= 50 的 completed gate）
    print("[benchmark] using built-in benchmark texts")
    builtin_texts = [
        "The capital of France is Paris, a city known for the Eiffel Tower and the Louvre Museum.",
        "Machine learning is a subset of artificial intelligence that learns patterns from data.",
        "Natural language processing enables computers to understand and generate human language.",
        "Transformers have revolutionized the field of deep learning since their introduction in 2017.",
        "PyTorch is an open-source machine learning framework widely used in research and production.",
        "The attention mechanism allows models to focus on relevant parts of the input sequence.",
        "Language models can generate coherent and contextually relevant text given a prompt.",
        "The quick brown fox jumps over the lazy dog near the riverbank at dawn.",
        "Photosynthesis converts sunlight, water, and carbon dioxide into glucose and oxygen.",
        "The Great Wall of China stretches thousands of kilometers across mountains and deserts.",
        "Quantum computing leverages superposition and entanglement to process information in new ways.",
        "The human heart beats roughly one hundred thousand times per day, pumping blood through the body.",
        "Climate change is driven largely by greenhouse gas emissions from human activity.",
        "The Pacific Ocean is the largest and deepest ocean on Earth, covering about a third of the surface.",
        "Shakespeare wrote tragedies such as Hamlet, Macbeth, and King Lear in the early seventeenth century.",
        "The speed of light in a vacuum is approximately three hundred million meters per second.",
        "Bees communicate the location of flowers to their hive mates through a waggle dance.",
        "The Industrial Revolution began in Britain and transformed manufacturing, transport, and society.",
        "Deoxyribonucleic acid carries the genetic instructions used in the growth of all living organisms.",
        "Mount Everest is the tallest mountain above sea level, located in the Himalayas.",
        "The Roman Empire expanded across Europe, North Africa, and the Middle East at its peak.",
        "Electric vehicles store energy in rechargeable batteries and use electric motors for propulsion.",
        "The stock market reflects investor expectations about the future earnings of companies.",
        "Antibiotics are medicines that fight bacterial infections by killing or inhibiting bacteria.",
        "The theory of general relativity describes gravity as the curvature of spacetime.",
        "Rivers carry sediment from mountains to the sea, shaping landscapes over millennia.",
        "The Olympic Games bring together athletes from around the world every four years.",
        "Coffee is one of the most widely traded agricultural commodities in the world.",
        "The printing press invented by Gutenberg made books affordable and spread literacy across Europe.",
        "Volcanoes erupt when molten rock from deep within the Earth reaches the surface.",
        "The immune system defends the body against pathogens using a network of cells and organs.",
        "Renewable energy sources include solar, wind, hydro, and geothermal power.",
        "The Sahara Desert is the largest hot desert in the world, spanning much of North Africa.",
        "Symphonies, concertos, and sonatas are classical forms of musical composition.",
        "The internet connects billions of devices through a global network of routers and cables.",
        "Migration of birds occurs seasonally as they travel between breeding and wintering grounds.",
        "The Renaissance was a period of cultural and artistic flourishing that began in Italy.",
        "Glaciers form when accumulated snow compresses into dense ice over many centuries.",
        "Vaccines train the immune system to recognize and fight specific infectious diseases.",
        "The Amazon rainforest hosts an extraordinary diversity of plant and animal species.",
        "Supply and demand interact in markets to determine the prices of goods and services.",
        "The moon orbits the Earth roughly once every twenty-seven days, causing ocean tides.",
        "Fermentation is a metabolic process in which microorganisms convert sugars into acids or alcohol.",
        "The United Nations was founded in 1945 to promote international cooperation and peace.",
        "Coral reefs provide habitat for marine life but are threatened by warming oceans.",
        "The human brain contains billions of neurons connected by trillions of synapses.",
        "Agriculture developed independently in several regions of the world thousands of years ago.",
        "Satellites orbit the Earth for communication, navigation, weather monitoring, and research.",
        "The rule of law requires that governments and citizens alike are subject to publicly disclosed laws.",
        "Plate tectonics explains the movement of the Earth's crust and the occurrence of earthquakes.",
        "Libraries provide public access to books, digital media, and community learning programs.",
        "The water cycle describes the continuous movement of water between the ocean, atmosphere, and land.",
        "Chess is a strategic board game played between two opponents on a checkered board.",
        "The Hubble Space Telescope has captured detailed images of distant galaxies and nebulae.",
        "Coral bleaching occurs when stressed corals expel the algae living in their tissues.",
        "The Silk Road was an ancient network of trade routes connecting East Asia and the Mediterranean.",
        "Wind turbines convert kinetic energy from moving air into electrical power.",
        "The periodic table organizes chemical elements by atomic number and recurring properties.",
        "Urban planning shapes how cities allocate land for housing, transport, and public spaces.",
        "The discovery of penicillin marked the beginning of modern antibiotic medicine.",
        "Mangrove forests protect coastlines from erosion and serve as nurseries for fish.",
        "The central bank manages monetary policy by setting interest rates and regulating money supply.",
        "Meteorologists use satellite data and computer models to forecast weather patterns.",
        "The ancient library of Alexandria was one of the largest centers of learning in the ancient world.",
    ]
    return builtin_texts, "builtin"


# ============================================================
# Device Selection Logic (NPU > CUDA > CPU)
# ============================================================
def get_device(force_cpu: bool = False):
    """获取推理设备。若 force_cpu=True，强制返回 CPU。

    默认优先级: NPU > CUDA > CPU
    NPU 选卡: 用 torch.npu.mem_get_info() 遍历各卡，选空闲（free 显存最大）的卡。
    本机严禁设置 ASCEND_RT_VISIBLE_DEVICES，选卡一律用 torch.npu.set_device()。
    """
    if force_cpu:
        return "cpu", 0, "cpu"

    try:
        import torch_npu  # noqa: F401

        if hasattr(torch, "npu") and torch.npu.is_available():
            count = torch.npu.device_count()
            best_index = 0
            best_free = -1
            for i in range(count):
                try:
                    free, total = torch.npu.mem_get_info(i)
                except Exception:
                    free, total = 0, 0
                print(f"[Device] NPU {i}: free={free / 1024**3:.2f}GB / total={total / 1024**3:.2f}GB")
                if free > best_free:
                    best_free = free
                    best_index = i
            print(f"[Device] Huawei Ascend NPU detected; selected idle device npu:{best_index}")
            torch.npu.set_device(best_index)
            device_name = torch.npu.get_device_name(best_index)
            return f"npu:{best_index}", count, device_name
    except ImportError:
        pass

    if torch.cuda.is_available():
        device_name = torch.cuda.get_device_name(0)
        return "cuda:0", torch.cuda.device_count(), device_name
    return "cpu", 0, "cpu"


class _PerfMonitor:
    """性能监控器：测量推理延迟和峰值内存"""

    def __init__(self, device_type, device_ids=None):
        self.device_type = device_type
        self.device_ids = device_ids
        self.start = None
        self.latency_s = None
        self.peak_memory_mb = None

    def __enter__(self):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401

            torch.npu.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.npu.reset_peak_memory_stats(dev_id)
            else:
                torch.npu.reset_peak_memory_stats()
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.cuda.reset_peak_memory_stats(dev_id)
            else:
                torch.cuda.reset_peak_memory_stats()

        self.start = time.perf_counter()
        return self

    def __exit__(self, *args):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401

            torch.npu.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.npu.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.npu.max_memory_allocated() / (1024**2)
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.cuda.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.cuda.max_memory_allocated() / (1024**2)
        else:
            self.peak_memory_mb = 0.0

        self.latency_s = time.perf_counter() - self.start
        return False


def get_profiler_context(device_short):
    """根据硬件动态返回原生 Profiler 上下文"""
    if device_short == "npu":
        import torch_npu  # noqa: F401
        from torch_npu.profiler import ProfilerActivity as NPUActivity
        from torch_npu.profiler import profile as npu_profile

        activities = [NPUActivity.CPU, NPUActivity.NPU]
        return npu_profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)
    else:
        activities = [torch.profiler.ProfilerActivity.CPU]
        if device_short == "cuda":
            activities.append(torch.profiler.ProfilerActivity.CUDA)

        return torch.profiler.profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)


def get_dtype_str(dtype: torch.dtype) -> str:
    """Convert torch dtype to short string (fp32, fp16, bf16)."""
    dtype_map = {
        torch.float32: "fp32",
        torch.float16: "fp16",
        torch.bfloat16: "bf16",
        torch.int64: "int64",
        torch.int32: "int32",
    }
    return dtype_map.get(dtype, str(dtype).replace("torch.", ""))


def get_package_versions() -> dict:
    """获取关键依赖包的版本"""
    import importlib.metadata

    packages = ["torch", "transformers", "torch_npu", "numpy", "datasets"]
    versions = {}
    for pkg in packages:
        try:
            versions[pkg] = importlib.metadata.version(pkg)
        except importlib.metadata.PackageNotFoundError:
            versions[pkg] = "not_installed"
    return versions


def setup_model(use_pretrained: bool, device, cache_dir: str):
    """加载模型 (MaskedLM / BERT)"""
    MODEL_ID = "google-bert/bert-base-uncased"

    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, cache_dir=cache_dir)
    config = AutoConfig.from_pretrained(MODEL_ID, cache_dir=cache_dir)

    if use_pretrained:
        model = AutoModelForMaskedLM.from_pretrained(MODEL_ID, cache_dir=cache_dir)
        model = model.to(device)
    else:
        model = AutoModelForMaskedLM.from_config(config)
        model = model.to(device)
    model.eval()

    return model, tokenizer


def build_masked_inputs(tokenizer, text: str, sample_index: int, device):
    """对单条文本做确定性 [MASK] 掩盖，返回 (inputs, selected_positions, original_ids)。

    - 仅掩盖非特殊 token（[CLS]/[SEP]/[PAD] 不参与）
    - 使用固定种子 (MASK_SEED_BASE + sample_index) 保证多次运行完全一致
    - 至少掩盖 1 个 token；若文本无可掩盖 token 返回 None
    """
    orig = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
    original_ids = orig["input_ids"]  # [1, L]

    special_ids = {tokenizer.cls_token_id, tokenizer.sep_token_id, tokenizer.pad_token_id}
    candidates = torch.ones(original_ids.shape[1], dtype=torch.bool)
    for sp in special_ids:
        if sp is not None:
            candidates &= original_ids[0] != sp
    cand_positions = candidates.nonzero(as_tuple=True)[0]
    if cand_positions.numel() == 0:
        return None, None, None

    gen = torch.Generator()
    gen.manual_seed(MASK_SEED_BASE + sample_index)
    rand_vals = torch.rand(cand_positions.numel(), generator=gen)
    selected = cand_positions[rand_vals < MASK_RATIO]
    if selected.numel() == 0:
        selected = cand_positions[:1]

    masked_ids = original_ids.clone()
    masked_ids[0, selected] = tokenizer.mask_token_id

    inputs = {k: v.to(device) for k, v in orig.items()}
    inputs["input_ids"] = masked_ids.to(device)
    return inputs, selected, original_ids


def run_step1(model, tokenizer, first_device, device_short, device_tag, device_ids, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str]):
    """Step 1: 单样本推理 -> trace_*.json + benchmark_metrics_*.json"""
    print("\n" + "=" * 60)
    print("Step 1: 单样本推理 (性能分析)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    trace_path = adapt_dir / f"trace_{device_tag}_{dtype_str}_{mode_str}_{dataset_name}.json"
    metrics_path = adapt_dir / f"benchmark_metrics_{device_tag}_{dtype_str}_{mode_str}_{dataset_name}.json"

    # 单样本（空数据集时使用 fallback）
    text = texts[0] if texts else "The capital of France is Paris."
    built = build_masked_inputs(tokenizer, text, 0, first_device)
    if built[0] is None:
        inputs, _, _ = build_masked_inputs(tokenizer, "The capital of France is Paris.", 0, first_device)
    else:
        inputs = built[0]

    profiler_context = get_profiler_context(device_short)

    start_time = datetime.now().isoformat()
    with profiler_context as prof:
        with _PerfMonitor(device_short, device_ids) as m:
            with torch.no_grad():
                out = model(**inputs)
                _ = out.logits  # MLM: logits over vocab at every position

        latency_s = m.latency_s
        peak_memory_mb = m.peak_memory_mb

    # 导出 trace
    prof.export_chrome_trace(str(trace_path))

    # 获取实际设备型号
    device_model = "unknown"
    if device_short == "npu" and first_device.index is not None:
        device_model = torch.npu.get_device_name(first_device.index)
    elif device_short == "cuda" and first_device.index is not None:
        device_model = torch.cuda.get_device_name(first_device.index)

    # 写入 metrics（end_time / ttft_ms / tpot_ms 将在 main() 末尾更新）
    metrics = {
        "start_time": start_time,
        "latency_s": round(latency_s, 6),
        "peak_memory_mb": round(peak_memory_mb, 2),
        "num_samples": len(texts),
        "device": str(first_device),
        "device_model": device_model,
        "mode": mode_str,
        "dataset": dataset_name,
        "dtype": dtype_str,
        "output_type": "generated_text",
        "packages": get_package_versions(),
    }
    metrics_path.write_text(json.dumps(metrics, indent=2))

    # 清理临时目录（忽略错误，NPU profiler 可能留下文件）
    prof_dir = adapt_dir / "export_only_prof_dir"
    if prof_dir.exists():
        shutil.rmtree(prof_dir, ignore_errors=True)
        print(f"[benchmark] cleaned up {prof_dir}")

    print(f"[benchmark] trace saved to {trace_path}")
    print(f"[benchmark] metrics saved to {metrics_path}")
    print(f"[benchmark] {metrics}")

    return trace_path, metrics_path, start_time


def run_step2(model, tokenizer, first_device, device_short, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str], max_samples: int = 250):
    """Step 2: 全样本推理 -> outputs_*.pt (MaskedLM, 非生成式)

    MLM 模型不测量 TTFT/TPOT，返回 None。

    画像方式:
    - [MASK] 填空: 掩盖 ~15% token 后 argmax 还原，保存填充后的文本
    - 伪困惑度: [MASK] 位置对原始 token 的交叉熵取 exp
    - logits: 首个 [MASK] 位置的完整 logits（算子精度对比用）

    内存优化：
    - 每个样本处理完后立即移动到 CPU
    - 每 32 个样本清理 NPU/CUDA 缓存
    - 默认限制样本数为 250（避免产出文件过大）

    输出格式 (outputs_*.pt, dict):
    - generated_text: [MASK] 填充还原后的文本列表
    - logits: 每样本首个 [MASK] 位置的 logits 张量列表
    - perplexity: 每样本伪困惑度列表

    Returns:
        tuple: (outputs_path, ttft_avg, tpot_avg) - MLM 模型 ttft_avg=None, tpot_avg=None
    """
    print("\n" + "=" * 60)
    print("Step 2: 全样本推理 (精度测试: [MASK] 填空 + 伪困惑度)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    outputs_path = adapt_dir / f"outputs_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.pt"

    # 限制样本数（R1 规则：最多 250 个样本）
    texts = texts[:max_samples]
    print(f"[benchmark] {len(texts)} samples to process (max {max_samples})")

    all_filled_texts = []
    all_logits = []
    all_ppl = []

    with torch.no_grad():
        for i, text in enumerate(texts):
            inputs, selected, original_ids = build_masked_inputs(tokenizer, text, i, first_device)
            if inputs is None:
                print(f"[benchmark] sample {i} has no maskable tokens, skipped")
                continue

            out = model(**inputs)
            logits = out.logits  # [1, L, V]

            mask_logits = logits[0, selected]  # [M, V]
            targets = original_ids[0, selected].to(first_device)  # [M]
            loss = F.cross_entropy(mask_logits, targets)
            ppl = torch.exp(loss).item()
            all_ppl.append(ppl)

            # [MASK] 填空: argmax 预测原词并还原句子
            pred_ids = mask_logits.argmax(dim=-1).cpu()
            filled_ids = original_ids.clone()
            filled_ids[0, selected] = pred_ids
            filled_text = tokenizer.decode(filled_ids[0], skip_special_tokens=True)
            all_filled_texts.append(filled_text)

            # 首个 [MASK] 位置完整 logits（CUDA/NPU 算子精度对比用）
            first_mask_logits = logits[0, selected[0]].cpu()
            all_logits.append(first_mask_logits)

            del out, logits, mask_logits, inputs

            # 每 32 个样本清理缓存（更频繁以避免 OOM）
            if (i + 1) % 32 == 0:
                if device_short == "npu":
                    torch.npu.empty_cache()
                elif device_short == "cuda":
                    torch.cuda.empty_cache()
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples (cache cleared)")
            elif (i + 1) % 8 == 0:
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples")

    # 保存 outputs（含 generated_text、logits 和 perplexity）
    output_data = {
        "generated_text": all_filled_texts,
        "logits": all_logits,
        "perplexity": all_ppl,
    }
    torch.save(output_data, outputs_path)

    ppl_avg = round(sum(all_ppl) / len(all_ppl), 2) if all_ppl else None
    print(f"[benchmark] outputs saved to {outputs_path}")
    print(f"[benchmark]   - generated_text ([MASK] filled): {len(all_filled_texts)} samples")
    if all_filled_texts:
        print(f"[benchmark]   - example: {all_filled_texts[0][:100]}")
    print(f"[benchmark]   - logits: {len(all_logits)} samples" + (f", shape: {tuple(all_logits[0].shape)}" if all_logits else ""))
    print(f"[benchmark]   - pseudo-perplexity: avg={ppl_avg}" + (f", min={min(all_ppl):.2f}, max={max(all_ppl):.2f}" if all_ppl else ""))

    return outputs_path, None, None  # MLM 不测量 TTFT/TPOT


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--use-pretrained", action="store_true", help="Tier2: load pretrained weights")
    parser.add_argument("--max-samples", type=int, default=250, help="Max samples to process (default 250, per R1 rule)")
    parser.add_argument("--cpu", action="store_true", help="Force CPU inference (disable NPU/CUDA)")
    args = parser.parse_args()

    CACHE_DIR = (Path(__file__).resolve().parent / "models").as_posix()
    ADAPT_DIR = Path(__file__).resolve().parent

    # 1. Seed
    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    transformers_set_seed(SEED)
    device, _, _ = get_device(force_cpu=args.cpu)
    if device.startswith("npu"):
        torch.npu.manual_seed_all(SEED)
    elif device.startswith("cuda"):
        torch.cuda.manual_seed_all(SEED)

    # 开启全局确定性算法（确保 CUDA/NPU 输出一致）
    torch.use_deterministic_algorithms(True, warn_only=True)

    # 仅在非 --cpu 模式下检查设备
    if not args.cpu:
        assert device.startswith(("npu", "cuda")), f"Need NPU or CUDA, got {device}"

    # 2. Load dataset
    texts, dataset_name = load_benchmark_texts()
    texts = texts[: args.max_samples]
    print(f"[benchmark] using dataset: {dataset_name}, samples selected: {len(texts)} (max_samples={args.max_samples})")

    # 3. Model
    model, tokenizer = setup_model(args.use_pretrained, device, CACHE_DIR)

    first_device = next(model.parameters()).device
    device_short = first_device.type
    device_tag = str(first_device).replace(":", "_")
    mode_str = "pretrained" if args.use_pretrained else "config"

    # 提取设备 IDs
    device_ids = None
    if first_device.index is not None:
        device_ids = [first_device.index]

    # Step 1: 单样本 -> trace + metrics
    trace_path, metrics_path, start_time = run_step1(model, tokenizer, first_device, device_short, device_tag, device_ids, mode_str, ADAPT_DIR, dataset_name, texts)

    # Step 2: 全样本 -> outputs（MLM 不测 TTFT/TPOT）
    outputs_path, ttft_avg, tpot_avg = run_step2(model, tokenizer, first_device, device_short, mode_str, ADAPT_DIR, dataset_name, texts, args.max_samples)

    # 更新 metrics 文件（添加 end_time, ttft_ms, tpot_ms）
    end_time = datetime.now().isoformat()
    with open(metrics_path, "r") as f:
        metrics = json.load(f)

    metrics["end_time"] = end_time
    metrics["ttft_ms"] = ttft_avg
    metrics["tpot_ms"] = tpot_avg

    with open(metrics_path, "w") as f:
        json.dump(metrics, indent=2, fp=f)

    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"  trace: {trace_path}")
    print(f"  metrics: {metrics_path}")
    print(f"  outputs: {outputs_path} (含 generated_text + logits + perplexity)")

    print(f"\nTo analyze NPU fallback, run:")
    print(f"   uv run python benchmark/scripts/benchmark_tool.py trace {trace_path.name}")
    print(f"   (add -v for detailed report, -j for JSON)")


if __name__ == "__main__":
    main()
