"""
Benchmark accuracy_run.py for google-t5/t5-small.
Generated by benchmark-runner. Modified by npu-optimizer for teacher-forcing contract.

Model Type: seq2seq (T5 text2text, encoder-decoder)
评测画像: 翻译 (EN->DE / EN->FR) + 摘要 (T5 任务前缀)

两步依次执行:
  Step 1: 单样本 teacher-forcing forward -> trace_*.json + benchmark_metrics_*.json (性能分析)
  Step 2: 全样本 teacher-forcing forward -> outputs_*.pt (精度测试: logits + perplexity)

Teacher-forcing 合同: 使用输入文本自身作为 encoder 输入和 decoder target，
  decoder_input_ids = model._shift_right(encoder_ids)，单次 forward 提取
  最后一个 token 的 logits 并以输入序列自身计算 perplexity (PPL = exp(CE))。
  相比 generate() 合同，forward 只需一次前向传播，可被 perf 脚本 batch 化加速。

Usage:
    uv run python accuracy_run.py                    # 完整执行 (step1 -> step2)
    uv run python accuracy_run.py --use-pretrained   # Tier2: 加载预训练权重
    uv run python accuracy_run.py --cpu              # 强制 CPU 推理 (禁用 NPU/CUDA)
"""

import argparse
import json
import os
import random
import shutil
import time
from datetime import datetime
from pathlib import Path

# 国内网络环境默认走 HF 镜像（外部已设置的环境变量优先）
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")
os.environ.setdefault("HF_HUB_DISABLE_XET", "1")

import numpy as np
import torch
from transformers import AutoConfig, AutoModelForSeq2SeqLM, AutoTokenizer
from transformers import set_seed as transformers_set_seed

from datasets import load_from_disk

# 数据集配置
DATASET_DIR = Path(__file__).resolve().parent.parent.parent / "datasets"
DATASET_TEXT_FIELD = "article"  # cnn_dailymail 的文本字段

MODEL_ID = "google-t5/t5-small"

WARMUP_ITERATIONS = 3


def load_benchmark_texts() -> tuple[list[str], str]:
    """加载测试数据集文本，返回 (texts, dataset_name)。

    T5 为 text2text 模型，输入必须带任务前缀（翻译/摘要画像）。
    优先级: 1. cnn_dailymail (本地) 2. 内置翻译/摘要样本
    """
    # 尝试加载 cnn_dailymail（加 summarize 前缀，适配 T5）
    cnn_path = DATASET_DIR / "cnn_dailymail___3.0.0"
    if cnn_path.exists():
        print(f"[benchmark] loading dataset from {cnn_path}")
        ds = load_from_disk(str(cnn_path))
        texts = sorted(["summarize: " + sample[DATASET_TEXT_FIELD] for sample in ds if sample[DATASET_TEXT_FIELD].strip()])
        print(f"[benchmark] loaded {len(texts)} samples from cnn_dailymail")
        return texts, "cnn_dailymail"

    # 降级到内置翻译/摘要样本（T5 text2text 任务前缀）
    print("[benchmark] using built-in benchmark texts (translate/summarize profile)")
    builtin_texts = [
        # ---- translate English to German (40) ----
        "translate English to German: The house is wonderful.",
        "translate English to German: I drink coffee every morning.",
        "translate English to German: She reads a book in the garden.",
        "translate English to German: The weather is nice today.",
        "translate English to German: We go to school by bus.",
        "translate English to German: He plays football with his friends.",
        "translate English to German: The cat sleeps on the sofa.",
        "translate English to German: My brother works in a hospital.",
        "translate English to German: They travel to Berlin every summer.",
        "translate English to German: The children sing a happy song.",
        "translate English to German: I like bread with butter and jam.",
        "translate English to German: The train arrives at noon.",
        "translate English to German: She writes a letter to her grandmother.",
        "translate English to German: The mountains are covered with snow.",
        "translate English to German: We eat dinner at seven o'clock.",
        "translate English to German: The dog runs quickly through the park.",
        "translate English to German: He buys fresh fruit at the market.",
        "translate English to German: The students learn French at school.",
        "translate English to German: My mother bakes a chocolate cake.",
        "translate English to German: The river flows through the old town.",
        "translate English to German: I watch the stars at night.",
        "translate English to German: The teacher explains the lesson clearly.",
        "translate English to German: They build a new bridge near the city.",
        "translate English to German: She dances to the music happily.",
        "translate English to German: The farmer feeds the animals every day.",
        "translate English to German: We visit our friends on Sunday.",
        "translate English to German: The library has many old books.",
        "translate English to German: He rides his bicycle to work.",
        "translate English to German: The soup tastes very good.",
        "translate English to German: I open the window in the morning.",
        "translate English to German: The birds fly over the lake.",
        "translate English to German: She wears a red dress to the party.",
        "translate English to German: The shop closes at six o'clock.",
        "translate English to German: We listen to music in the evening.",
        "translate English to German: The doctor helps sick people.",
        "translate English to German: He drinks tea with lemon.",
        "translate English to German: The garden is full of flowers.",
        "translate English to German: They celebrate the festival together.",
        "translate English to German: I walk to the market with my father.",
        "translate English to German: The moon shines brightly tonight.",
        # ---- translate English to French (14) ----
        "translate English to French: Good morning, my friend.",
        "translate English to French: The city is very beautiful.",
        "translate English to French: I love this small restaurant.",
        "translate English to French: She speaks three languages.",
        "translate English to French: The museum opens at nine.",
        "translate English to French: We need more time to decide.",
        "translate English to French: The sea is calm today.",
        "translate English to French: He cooks dinner for the family.",
        "translate English to French: The flowers smell wonderful.",
        "translate English to French: I lost my umbrella yesterday.",
        "translate English to French: The hotel is near the beach.",
        "translate English to French: They arrive tomorrow morning.",
        "translate English to French: The concert starts at eight.",
        "translate English to French: She smiles at the camera.",
        # ---- summarize (12) ----
        "summarize: The quick brown fox jumped over the lazy dog. The dog did not notice and kept sleeping. The fox ran away into the forest.",
        "summarize: Tom wanted to buy a new bicycle. He saved money for six months. Finally he bought a red bicycle and rode it to school.",
        "summarize: The city built a new park near the river. Families come to play and relax. The park is open every day.",
        "summarize: Scientists studied the sleep of students. They found that enough sleep improves memory. Students should sleep eight hours.",
        "summarize: A small bird built a nest in the tree. It laid three eggs in spring. The eggs hatched after two weeks.",
        "summarize: The farmer planted wheat in the field. It rained often during the summer. The harvest was very good this year.",
        "summarize: Anna learned to play the piano. She practiced every day after school. After one year she played her first concert.",
        "summarize: The old bridge was damaged by the flood. Workers repaired it during the winter. Now cars can cross the river again.",
        "summarize: A new library opened in the town center. It has books, computers and a reading room. Many people visit it every week.",
        "summarize: The team trained hard for the final match. They won the game two to one. The fans celebrated in the streets.",
        "summarize: Maria traveled to Italy last summer. She visited Rome and Venice. She enjoyed the food and the art.",
        "summarize: The school started a garden project. The children grow vegetables and flowers. They learn about nature and teamwork.",
    ]
    return builtin_texts, "builtin"


def select_idle_npu() -> int:
    """选择空闲 HBM 最多的 NPU 并设为当前设备。

    本机禁止设置 ASCEND_RT_VISIBLE_DEVICES（会导致 aclInit error 107001），
    因此通过 torch.npu.set_device() 在多卡中选定单卡。
    """
    count = torch.npu.device_count()
    best_idx, best_free = 0, -1
    for i in range(count):
        try:
            free, _total = torch.npu.mem_get_info(i)
        except Exception:
            free = 0
        print(f"[Device] NPU {i}: free HBM {free / 1024**3:.1f} GiB")
        if free > best_free:
            best_idx, best_free = i, free
    torch.npu.set_device(best_idx)
    return best_idx


def get_device(force_cpu: bool = False):
    """获取推理设备。若 force_cpu=True，强制返回 CPU。

    默认优先级: NPU > CUDA > CPU。
    NPU 多卡时自动选择空闲 HBM 最多的单卡（不设 ASCEND_RT_VISIBLE_DEVICES）。
    """
    if force_cpu:
        return "cpu", 0, "cpu"

    try:
        import torch_npu  # noqa: F401

        if hasattr(torch, "npu") and torch.npu.is_available():
            idx = select_idle_npu()
            device_name = torch.npu.get_device_name(idx)
            return f"npu:{idx}", torch.npu.device_count(), device_name
    except ImportError:
        pass
    if torch.cuda.is_available():
        device_name = torch.cuda.get_device_name(0)
        return "cuda:0", torch.cuda.device_count(), device_name
    return "cpu", 0, "cpu"


class _PerfMonitor:
    """性能监控器：测量推理延迟和峰值内存"""

    def __init__(self, device_type, device_ids=None):
        self.device_type = device_type
        self.device_ids = device_ids
        self.start = None
        self.latency_s = None
        self.peak_memory_mb = None

    def __enter__(self):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401

            torch.npu.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.npu.reset_peak_memory_stats(dev_id)
            else:
                torch.npu.reset_peak_memory_stats()
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.cuda.reset_peak_memory_stats(dev_id)
            else:
                torch.cuda.reset_peak_memory_stats()

        self.start = time.perf_counter()
        return self

    def __exit__(self, *args):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401

            torch.npu.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.npu.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.npu.max_memory_allocated() / (1024**2)
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.cuda.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.cuda.max_memory_allocated() / (1024**2)
        else:
            self.peak_memory_mb = 0.0

        self.latency_s = time.perf_counter() - self.start
        return False


def get_profiler_context(device_short):
    """根据硬件动态返回原生 Profiler 上下文"""
    if device_short == "npu":
        import torch_npu  # noqa: F401
        from torch_npu.profiler import ProfilerActivity as NPUActivity
        from torch_npu.profiler import profile as npu_profile

        activities = [NPUActivity.CPU, NPUActivity.NPU]
        return npu_profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)
    else:
        activities = [torch.profiler.ProfilerActivity.CPU]
        if device_short == "cuda":
            activities.append(torch.profiler.ProfilerActivity.CUDA)

        return torch.profiler.profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)


def get_dtype_str(dtype: torch.dtype) -> str:
    """Convert torch dtype to short string (fp32, fp16, bf16)."""
    dtype_map = {
        torch.float32: "fp32",
        torch.float16: "fp16",
        torch.bfloat16: "bf16",
        torch.int64: "int64",
        torch.int32: "int32",
    }
    return dtype_map.get(dtype, str(dtype).replace("torch.", ""))


def get_package_versions() -> dict:
    """获取关键依赖包的版本"""
    import importlib.metadata

    packages = ["torch", "transformers", "torch_npu", "numpy", "datasets"]
    versions = {}
    for pkg in packages:
        try:
            versions[pkg] = importlib.metadata.version(pkg)
        except importlib.metadata.PackageNotFoundError:
            versions[pkg] = "not_installed"
    return versions


def setup_model(use_pretrained: bool, device, cache_dir: str):
    """加载模型 (Seq2Seq, T5)"""
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, cache_dir=cache_dir)
    config = AutoConfig.from_pretrained(MODEL_ID, cache_dir=cache_dir)

    if use_pretrained:
        model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_ID, torch_dtype="auto", cache_dir=cache_dir)
        model = model.to(device)
    else:
        model = AutoModelForSeq2SeqLM.from_config(config)
        model = model.to(device)
    model.eval()

    return model, tokenizer


def run_step1(model, tokenizer, first_device, device_short, device_ids, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str], num_samples: int):
    """Step 1: 单样本 teacher-forcing forward -> trace_*.json + benchmark_metrics_*.json

    T5 为 encoder-decoder：用 teacher-forcing forward 作为被 trace 的推理负载。
    decoder_input_ids = model._shift_right(encoder_ids)，单次前向传播。
    """
    print("\n" + "=" * 60)
    print("Step 1: 单样本 teacher-forcing forward (性能分析)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    trace_path = adapt_dir / f"trace_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"
    metrics_path = adapt_dir / f"benchmark_metrics_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"

    # 单样本
    text = texts[0] if texts else "translate English to German: Hello, benchmark."
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(first_device)
    encoder_ids = inputs.input_ids
    decoder_input_ids = model._shift_right(encoder_ids)

    profiler_context = get_profiler_context(device_short)

    start_time = datetime.now().isoformat()
    with profiler_context as prof:
        with _PerfMonitor(device_short, device_ids) as m:
            with torch.no_grad():
                outputs = model(input_ids=encoder_ids, decoder_input_ids=decoder_input_ids)
                _ = outputs.logits.shape  # 仅推理，不保存

        latency_s = m.latency_s
        peak_memory_mb = m.peak_memory_mb

    # 导出 trace
    prof.export_chrome_trace(str(trace_path))

    # 获取实际设备型号
    device_model = "unknown"
    if device_short == "npu" and first_device.index is not None:
        device_model = torch.npu.get_device_name(first_device.index)
    elif device_short == "cuda" and first_device.index is not None:
        device_model = torch.cuda.get_device_name(first_device.index)

    # 写入 metrics（end_time/wall_clock_s 将在 main() 末尾更新）
    metrics = {
        "start_time": start_time,
        "latency_s": round(latency_s, 6),
        "peak_memory_mb": round(peak_memory_mb, 2),
        "num_samples": num_samples,
        "device": str(first_device),
        "device_model": device_model,
        "mode": mode_str,
        "dataset": dataset_name,
        "dtype": dtype_str,
        "output_type": "logits",
        "warmup_iterations": WARMUP_ITERATIONS,
        "packages": get_package_versions(),
    }
    metrics_path.write_text(json.dumps(metrics, indent=2))

    # 清理临时目录（忽略错误，NPU profiler 可能留下文件）
    prof_dir = adapt_dir / "export_only_prof_dir"
    if prof_dir.exists():
        shutil.rmtree(prof_dir, ignore_errors=True)
        print(f"[benchmark] cleaned up {prof_dir}")

    print(f"[benchmark] trace saved to {trace_path}")
    print(f"[benchmark] metrics saved to {metrics_path}")
    print(f"[benchmark] {metrics}")

    return trace_path, metrics_path, start_time


def run_step2(model, tokenizer, first_device, device_short, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str], max_samples: int = 250):
    """Step 2: 全样本 teacher-forcing forward -> outputs_*.pt (logits + perplexity)

    每个样本:
    1. Tokenize text -> encoder_ids
    2. decoder_input_ids = model._shift_right(encoder_ids)
    3. forward(input_ids=encoder_ids, decoder_input_ids=decoder_input_ids) -> logits
    4. 提取最后一个 token 的 logits，计算 perplexity (PPL = exp(CE))

    输出格式 (outputs_*.pt):
    - logits: 每个样本最后一个 token 的 logits 张量列表
    - perplexity: 每个样本的 perplexity 值列表

    Returns:
        tuple: (outputs_path, wall_clock_s, warmup_iterations)
    """
    print("\n" + "=" * 60)
    print("Step 2: 全样本 teacher-forcing forward (精度测试: logits + PPL)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    outputs_path = adapt_dir / f"outputs_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.pt"

    # 限制样本数（R1 规则：最多 250 个样本）
    texts = texts[:max_samples]
    print(f"[benchmark] {len(texts)} samples to process (max {max_samples})")

    vocab_size = model.config.vocab_size

    # Warmup: 使用第一个样本做 WARMUP_ITERATIONS 次前向
    dummy_text = texts[0] if texts else "translate English to German: Hello."
    dummy_inputs = tokenizer(dummy_text, return_tensors="pt", truncation=True, max_length=512).to(first_device)
    dummy_decoder = model._shift_right(dummy_inputs.input_ids)
    print(f"[benchmark] warming up ({WARMUP_ITERATIONS} iterations)...")
    for _ in range(WARMUP_ITERATIONS):
        with torch.no_grad():
            _ = model(input_ids=dummy_inputs.input_ids, decoder_input_ids=dummy_decoder)

    if device_short == "npu":
        torch.npu.synchronize()
    elif device_short == "cuda":
        torch.cuda.synchronize()

    # 计时推理
    step2_start = time.perf_counter()

    all_logits = []
    all_ppl = []

    with torch.no_grad():
        for i, text in enumerate(texts):
            inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(first_device)
            encoder_ids = inputs.input_ids
            decoder_input_ids = model._shift_right(encoder_ids)
            labels = encoder_ids.clone()

            outputs = model(input_ids=encoder_ids, decoder_input_ids=decoder_input_ids)
            last_token_logits = outputs.logits[0, -1, :].cpu()  # [vocab_size]
            all_logits.append(last_token_logits)

            # PPL = exp(cross_entropy_loss)，以输入序列自身为目标
            loss_fct = torch.nn.CrossEntropyLoss(reduction="mean")
            loss = loss_fct(
                outputs.logits[0].view(-1, vocab_size),
                labels[0].view(-1),
            )
            ppl = torch.exp(loss).item()
            all_ppl.append(ppl)
            del outputs, inputs, encoder_ids, decoder_input_ids, labels

            # 每 16 个样本清理缓存
            if (i + 1) % 16 == 0:
                if device_short == "npu":
                    torch.npu.empty_cache()
                elif device_short == "cuda":
                    torch.cuda.empty_cache()
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples (cache cleared)")
            elif (i + 1) % 8 == 0:
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples")

    if device_short == "npu":
        torch.npu.synchronize()
    elif device_short == "cuda":
        torch.cuda.synchronize()

    step2_end = time.perf_counter()
    wall_clock_s = step2_end - step2_start

    # 保存 outputs（包含 logits 和 perplexity）
    output_data = {
        "logits": all_logits,
        "perplexity": all_ppl,
    }
    torch.save(output_data, outputs_path)

    # 计算 PPL 统计
    ppl_avg = round(sum(all_ppl) / len(all_ppl), 2) if all_ppl else None

    print(f"[benchmark] outputs saved to {outputs_path}")
    print(f"[benchmark]   - logits: {len(all_logits)} samples, shape: {all_logits[0].shape}")
    print(f"[benchmark]   - perplexity: avg={ppl_avg}")
    print(f"[benchmark] wall_clock_s: {wall_clock_s:.6f}")

    return outputs_path, wall_clock_s, WARMUP_ITERATIONS


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--use-pretrained", action="store_true", help="Tier2: load pretrained weights")
    parser.add_argument("--max-samples", type=int, default=250, help="Max samples to process (default 250, per R1 rule)")
    parser.add_argument("--cpu", action="store_true", help="Force CPU inference (disable NPU/CUDA)")
    args = parser.parse_args()

    CACHE_DIR = (Path(__file__).resolve().parent / "models").as_posix()
    ADAPT_DIR = Path(__file__).resolve().parent

    # 1. Seed
    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    transformers_set_seed(SEED)
    device, _, _ = get_device(force_cpu=args.cpu)
    if device.startswith("npu"):
        torch.npu.manual_seed_all(SEED)
    elif device.startswith("cuda"):
        torch.cuda.manual_seed_all(SEED)

    # 开启全局确定性算法（确保 CUDA/NPU 输出一致）
    torch.use_deterministic_algorithms(True, warn_only=True)

    # 仅在非 --cpu 模式下检查设备
    if not args.cpu:
        assert device.startswith(("npu", "cuda")), f"Need NPU or CUDA, got {device}"

    # 2. Load dataset
    texts, dataset_name = load_benchmark_texts()
    print(f"[benchmark] using dataset: {dataset_name}, total samples: {len(texts)}, max_samples: {args.max_samples}")

    # 3. Model
    model, tokenizer = setup_model(args.use_pretrained, device, CACHE_DIR)

    first_device = next(model.parameters()).device
    device_short = str(first_device).replace(":", "_")
    perf_device_short = first_device.type
    mode_str = "pretrained" if args.use_pretrained else "config"

    # 实际参与统计的样本数（与 Step 2 截断保持一致）
    num_samples = min(len(texts), args.max_samples)

    # 提取设备 IDs
    device_ids = None
    if hasattr(model, "hf_device_map"):
        device_ids = list(set(dev.index if hasattr(dev, "index") else dev for dev in model.hf_device_map.values()))
    elif first_device.index is not None:
        device_ids = [first_device.index]

    # Step 1: 单样本 -> trace + metrics
    trace_path, metrics_path, start_time = run_step1(model, tokenizer, first_device, perf_device_short, device_ids, mode_str, ADAPT_DIR, dataset_name, texts, num_samples)

    # Step 2: 全样本 -> outputs (logits + perplexity)
    outputs_path, wall_clock_s, warmup_iters = run_step2(model, tokenizer, first_device, perf_device_short, mode_str, ADAPT_DIR, dataset_name, texts, args.max_samples)

    # 更新 metrics 文件（添加 end_time, wall_clock_s, 更新 latency_s 为 per-sample）
    end_time = datetime.now().isoformat()
    with open(metrics_path, "r") as f:
        metrics = json.load(f)

    metrics["end_time"] = end_time
    metrics["wall_clock_s"] = round(wall_clock_s, 6)
    metrics["warmup_iterations"] = warmup_iters
    # latency_s 更新为 per-sample wall-clock（step2 总时长 / 样本数）
    latency_per_sample = wall_clock_s / num_samples if num_samples > 0 else wall_clock_s
    metrics["latency_s"] = round(latency_per_sample, 6)

    with open(metrics_path, "w") as f:
        json.dump(metrics, indent=2, fp=f)

    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"  trace: {trace_path}")
    print(f"  metrics: {metrics_path}")
    print(f"  outputs: {outputs_path} (含 logits + perplexity)")
    print(f"  wall_clock_s: {wall_clock_s:.6f}")
    print(f"  latency_s (per-sample): {latency_per_sample:.6f}")

    print(f"\nTo analyze NPU fallback, run:")
    print(f"   uv run python benchmark/scripts/benchmark_tool.py trace {trace_path.name}")


if __name__ == "__main__":
    main()
