"""
Benchmark accuracy_run.py for FacebookAI/roberta-base.
Generated by benchmark-runner. Dimension 2 (accuracy .pt) + 3 (perf) + 4 (trace, required).

Teacher-forcing 合同：单步前向获取 mask 位置 logits，不做伪困惑度。
Step 1: 单样本 -> trace_*.json + benchmark_metrics_*.json (性能分析)
Step 2: 全样本 -> outputs_*.pt (精度测试: mask 位置 logits)

Model Type: masked LM (RoBERTa encoder, 非生成式)
Recommended Dataset: builtin (fill-mask)
"""

import argparse
import json
import os
import random
import shutil
import time
from datetime import datetime
from pathlib import Path

# 国内网络环境默认走 HF 镜像（外部已设置的环境变量优先）
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")
os.environ.setdefault("HF_HUB_DISABLE_XET", "1")

import numpy as np
import torch
from transformers import AutoConfig, AutoModelForMaskedLM, AutoTokenizer
from transformers import set_seed as transformers_set_seed

MODEL_ID = "FacebookAI/roberta-base"


def load_benchmark_texts() -> tuple[list[str], str]:
    """加载 MLM 评测文本（每条恰好含一个 <mask>），返回 (texts, dataset_name)。"""
    print("[benchmark] using built-in benchmark texts (fill-mask profile)")
    builtin_texts = [
        "The capital of France is <mask>.",
        "The largest planet in our solar system is <mask>.",
        "The Great Wall is located in <mask>.",
        "The river <mask> flows through Egypt.",
        "Mount Everest is the highest <mask> on Earth.",
        "The official language of Brazil is <mask>.",
        "Tokyo is the capital of <mask>.",
        "The Sahara is the largest hot <mask> in the world.",
        "The Pacific is the largest <mask> on Earth.",
        "Berlin is the capital of <mask>.",
        "Water freezes at zero degrees <mask>.",
        "The chemical symbol for gold is <mask>.",
        "Plants use sunlight to make food through <mask>.",
        "The speed of light is about 300,000 kilometers per <mask>.",
        "Humans have <mask> chromosomes in each cell.",
        "The Earth revolves around the <mask> once a year.",
        "The Moon orbits around the <mask>.",
        "Sound travels through the air as <mask>.",
        "The human body needs <mask> to breathe.",
        "Ice is the solid form of <mask>.",
        "I drink a cup of <mask> every morning.",
        "She reads the <mask> to learn the latest news.",
        "He went to the <mask> to buy fresh vegetables.",
        "We use a <mask> to tell the time.",
        "The children play football in the <mask>.",
        "My grandmother bakes delicious <mask> pie.",
        "The doctor gave him a <mask> for the pain.",
        "She took the <mask> to the airport.",
        "He opened the <mask> to let in fresh air.",
        "The restaurant serves Italian <mask>.",
        "William Shakespeare wrote many famous <mask>.",
        "The piano is a musical <mask>.",
        "The Mona Lisa was painted by Leonardo da <mask>.",
        "The Olympic Games are held every four <mask>.",
        "People celebrate Christmas in <mask>.",
        "The first man on the Moon was Neil <mask>.",
        "Beethoven was a famous <mask>.",
        "The ancient pyramids were built in <mask>.",
        "Chess is a game of <mask>.",
        "The violin has four <mask>.",
        "The teacher wrote the answer on the <mask>.",
        "Students must pass the <mask> to graduate.",
        "The meeting will start at nine <mask>.",
        "He works as an engineer at a technology <mask>.",
        "The library has thousands of <mask>.",
        "She finished her homework before <mask>.",
        "The scientist published the results of the <mask>.",
        "The nurse works in a <mask>.",
        "The farmer grows <mask> in the field.",
        "The pilot flew the plane across the <mask>.",
        "The opposite of hot is <mask>.",
        "A week has seven <mask>.",
        "There are twelve months in a <mask>.",
        "The color of the sky on a clear day is <mask>.",
        "Birds build their nests in <mask>.",
        "Fish live in the <mask>.",
        "Bees make <mask> from flowers.",
        "A person who writes books is called an <mask>.",
        "The season after winter is <mask>.",
        "We celebrate the new year in <mask>.",
    ]
    return builtin_texts, "builtin"


def select_idle_npu() -> int:
    """选择空闲 HBM 最多的 NPU 并设为当前设备。"""
    count = torch.npu.device_count()
    best_idx, best_free = 0, -1
    for i in range(count):
        try:
            free, _total = torch.npu.mem_get_info(i)
        except Exception:
            free = 0
        print(f"[Device] NPU {i}: free HBM {free / 1024**3:.1f} GiB")
        if free > best_free:
            best_idx, best_free = i, free
    torch.npu.set_device(best_idx)
    return best_idx


def get_device(force_cpu: bool = False):
    """获取推理设备。"""
    if force_cpu:
        return "cpu", 0, "cpu"
    try:
        import torch_npu  # noqa: F401
        if hasattr(torch, "npu") and torch.npu.is_available():
            idx = select_idle_npu()
            device_name = torch.npu.get_device_name(idx)
            return f"npu:{idx}", torch.npu.device_count(), device_name
    except ImportError:
        pass
    if torch.cuda.is_available():
        device_name = torch.cuda.get_device_name(0)
        return "cuda:0", torch.cuda.device_count(), device_name
    return "cpu", 0, "cpu"


class _PerfMonitor:
    """性能监控器：测量推理延迟和峰值内存"""

    def __init__(self, device_type, device_ids=None):
        self.device_type = device_type
        self.device_ids = device_ids
        self.start = None
        self.latency_s = None
        self.peak_memory_mb = None

    def __enter__(self):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401
            torch.npu.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.npu.reset_peak_memory_stats(dev_id)
            else:
                torch.npu.reset_peak_memory_stats()
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.cuda.reset_peak_memory_stats(dev_id)
            else:
                torch.cuda.reset_peak_memory_stats()
        self.start = time.perf_counter()
        return self

    def __exit__(self, *args):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401
            torch.npu.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.npu.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.npu.max_memory_allocated() / (1024**2)
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.cuda.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.cuda.max_memory_allocated() / (1024**2)
        else:
            self.peak_memory_mb = 0.0
        self.latency_s = time.perf_counter() - self.start
        return False


def get_profiler_context(device_short):
    """根据硬件动态返回原生 Profiler 上下文"""
    if device_short == "npu":
        import torch_npu  # noqa: F401
        from torch_npu.profiler import ProfilerActivity as NPUActivity
        from torch_npu.profiler import profile as npu_profile
        activities = [NPUActivity.CPU, NPUActivity.NPU]
        return npu_profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)
    else:
        activities = [torch.profiler.ProfilerActivity.CPU]
        if device_short == "cuda":
            activities.append(torch.profiler.ProfilerActivity.CUDA)
        return torch.profiler.profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)


def get_dtype_str(dtype: torch.dtype) -> str:
    dtype_map = {
        torch.float32: "fp32",
        torch.float16: "fp16",
        torch.bfloat16: "bf16",
        torch.int64: "int64",
        torch.int32: "int32",
    }
    return dtype_map.get(dtype, str(dtype).replace("torch.", ""))


def get_package_versions() -> dict:
    import importlib.metadata
    packages = ["torch", "transformers", "torch_npu", "numpy", "datasets"]
    versions = {}
    for pkg in packages:
        try:
            versions[pkg] = importlib.metadata.version(pkg)
        except importlib.metadata.PackageNotFoundError:
            versions[pkg] = "not_installed"
    return versions


def setup_model(use_pretrained: bool, device, cache_dir: str):
    """加载模型 (MaskedLM, RoBERTa)"""
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, cache_dir=cache_dir)
    config = AutoConfig.from_pretrained(MODEL_ID, cache_dir=cache_dir)
    if use_pretrained:
        model = AutoModelForMaskedLM.from_pretrained(MODEL_ID, cache_dir=cache_dir)
        model = model.to(device)
    else:
        model = AutoModelForMaskedLM.from_config(config)
        model = model.to(device)
    model.eval()
    return model, tokenizer


def run_step1(model, tokenizer, first_device, device_short, device_ids, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str], num_samples: int):
    """Step 1: 单样本推理 -> trace_*.json + benchmark_metrics_*.json"""
    print("\n" + "=" * 60)
    print("Step 1: 单样本推理 (性能分析)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    trace_path = adapt_dir / f"trace_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"
    metrics_path = adapt_dir / f"benchmark_metrics_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"

    text = texts[0] if texts else "The capital of France is <mask>."
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(first_device)

    profiler_context = get_profiler_context(device_short)

    start_time = datetime.now().isoformat()
    with profiler_context as prof:
        with _PerfMonitor(device_short, device_ids) as m:
            with torch.no_grad():
                out = model(**inputs)
                _ = out.logits
        latency_s = m.latency_s
        peak_memory_mb = m.peak_memory_mb

    prof.export_chrome_trace(str(trace_path))

    device_model = "unknown"
    if device_short == "npu" and first_device.index is not None:
        device_model = torch.npu.get_device_name(first_device.index)
    elif device_short == "cuda" and first_device.index is not None:
        device_model = torch.cuda.get_device_name(first_device.index)

    metrics = {
        "start_time": start_time,
        "latency_s": round(latency_s, 6),
        "step1_forward_latency_s": round(latency_s, 6),
        "peak_memory_mb": round(peak_memory_mb, 2),
        "num_samples": num_samples,
        "device": str(first_device),
        "device_model": device_model,
        "mode": mode_str,
        "dataset": dataset_name,
        "dtype": dtype_str,
        "output_type": "logits",
        "packages": get_package_versions(),
    }
    metrics_path.write_text(json.dumps(metrics, indent=2))

    prof_dir = adapt_dir / "export_only_prof_dir"
    if prof_dir.exists():
        shutil.rmtree(prof_dir, ignore_errors=True)
        print(f"[benchmark] cleaned up {prof_dir}")

    print(f"[benchmark] trace saved to {trace_path}")
    print(f"[benchmark] metrics saved to {metrics_path}")
    print(f"[benchmark] {metrics}")
    return trace_path, metrics_path, start_time


def run_step2(model, tokenizer, first_device, device_short, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str], max_samples: int = 250):
    """Step 2: 全样本前向 -> outputs_*.pt (mask 位置 logits)

    对每个样本做单步前向，提取 <mask> 位置的 logits。
    不做伪困惑度（控制开销，使 batch 化可行）。
    """
    print("\n" + "=" * 60)
    print("Step 2: 全样本前向 (mask 位置 logits)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    outputs_path = adapt_dir / f"outputs_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.pt"

    texts = texts[:max_samples]
    print(f"[benchmark] {len(texts)} samples to process (max {max_samples})")

    mask_token_id = tokenizer.mask_token_id
    all_logits = []
    all_sample_latency = []

    # warmup: 3 次前向预热（不计入计时）
    warmup_iterations = 3
    print(f"[benchmark] warmup {warmup_iterations} iterations...")
    warmup_text = texts[0] if texts else "The capital of France is <mask>."
    warmup_inputs = tokenizer(warmup_text, return_tensors="pt", truncation=True, max_length=512).to(first_device)
    with torch.no_grad():
        for _ in range(warmup_iterations):
            _ = model(**warmup_inputs)
    if device_short == "npu":
        torch.npu.synchronize()
    elif device_short == "cuda":
        torch.cuda.synchronize()
    print(f"[benchmark] warmup done")

    step2_start = time.perf_counter()

    with torch.no_grad():
        for i, text in enumerate(texts):
            sample_start = time.perf_counter()
            inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(first_device)
            input_ids = inputs["input_ids"]

            out = model(**inputs)
            logits = out.logits  # [1, seq_len, vocab]

            mask_positions = (input_ids == mask_token_id).nonzero(as_tuple=True)
            if len(mask_positions[1]) == 1:
                mask_pos = int(mask_positions[1][0])
                mask_logits = logits[0, mask_pos].cpu()  # [vocab_size]
                all_logits.append(mask_logits)
            else:
                all_logits.append(torch.zeros(model.config.vocab_size, dtype=torch.float32))

            all_sample_latency.append(time.perf_counter() - sample_start)

            del inputs, input_ids, out, logits

            if (i + 1) % 32 == 0:
                if device_short == "npu":
                    torch.npu.empty_cache()
                elif device_short == "cuda":
                    torch.cuda.empty_cache()
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples (cache cleared)")
            elif (i + 1) % 8 == 0:
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples")

    step2_end = time.perf_counter()
    wall_clock_s = round(step2_end - step2_start, 6)

    output_data = {
        "logits": all_logits,
    }
    torch.save(output_data, outputs_path)

    avg_latency_s = round(sum(all_sample_latency) / len(all_sample_latency), 6) if all_sample_latency else None

    print(f"[benchmark] outputs saved to {outputs_path}")
    print(f"[benchmark]   - logits: {len(all_logits)} samples, shape: {all_logits[0].shape}")
    print(f"[benchmark] wall_clock_s: {wall_clock_s}")
    print(f"[benchmark] avg per-sample latency: {avg_latency_s} s")

    return outputs_path, avg_latency_s, wall_clock_s, warmup_iterations


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--use-pretrained", action="store_true", help="Tier2: load pretrained weights")
    parser.add_argument("--max-samples", type=int, default=250, help="Max samples to process (default 250, per R1 rule)")
    parser.add_argument("--cpu", action="store_true", help="Force CPU inference (disable NPU/CUDA)")
    args = parser.parse_args()

    CACHE_DIR = (Path(__file__).resolve().parent / "models").as_posix()
    ADAPT_DIR = Path(__file__).resolve().parent

    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    transformers_set_seed(SEED)
    device, _, _ = get_device(force_cpu=args.cpu)
    if device.startswith("npu"):
        torch.npu.manual_seed_all(SEED)
    elif device.startswith("cuda"):
        torch.cuda.manual_seed_all(SEED)

    torch.use_deterministic_algorithms(True, warn_only=True)

    if not args.cpu:
        assert device.startswith(("npu", "cuda")), f"Need NPU or CUDA, got {device}"

    texts, dataset_name = load_benchmark_texts()
    texts = texts[: args.max_samples]
    print(f"[benchmark] using dataset: {dataset_name}, total samples: {len(texts)}, max_samples: {args.max_samples}")

    model, tokenizer = setup_model(args.use_pretrained, device, CACHE_DIR)

    first_device = next(model.parameters()).device
    device_short = first_device.type
    mode_str = "pretrained" if args.use_pretrained else "config"

    num_samples = min(len(texts), args.max_samples)

    device_ids = None
    if hasattr(model, "hf_device_map"):
        device_ids = list(set(dev.index if hasattr(dev, "index") else dev for dev in model.hf_device_map.values()))
    elif first_device.index is not None:
        device_ids = [first_device.index]

    trace_path, metrics_path, start_time = run_step1(model, tokenizer, first_device, device_short, device_ids, mode_str, ADAPT_DIR, dataset_name, texts, num_samples)

    outputs_path, avg_latency_s, wall_clock_s, warmup_iterations = run_step2(model, tokenizer, first_device, device_short, mode_str, ADAPT_DIR, dataset_name, texts, args.max_samples)

    end_time = datetime.now().isoformat()
    with open(metrics_path, "r") as f:
        metrics = json.load(f)

    metrics["end_time"] = end_time
    metrics["wall_clock_s"] = wall_clock_s
    metrics["warmup_iterations"] = warmup_iterations
    if avg_latency_s is not None:
        metrics["latency_s"] = avg_latency_s

    with open(metrics_path, "w") as f:
        json.dump(metrics, indent=2, fp=f)

    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"  ✅ trace: {trace_path}")
    print(f"  ✅ metrics: {metrics_path}")
    print(f"  ✅ outputs: {outputs_path} (含 mask 位置 logits)")
    print(f"  📊 wall_clock_s: {wall_clock_s}, avg latency: {avg_latency_s} s")


if __name__ == "__main__":
    main()
