"""
Benchmark accuracy_run.py for FacebookAI/roberta-base.
Generated by benchmark-runner. Dimension 2 (accuracy .pt) + 3 (perf) + 4 (trace, required).

Model Type: masked LM (RoBERTa encoder, 非生成式)
评测画像: [MASK] 填空 (fill-mask) + 伪困惑度 (pseudo-perplexity)

两步依次执行:
  Step 1: 单样本 -> trace_*.json + benchmark_metrics_*.json (性能分析)
  Step 2: 全样本 -> outputs_*.pt (精度测试)

注意: RoBERTa 为 masked LM（非生成式），不测 TTFT/TPOT（metrics 中为 null）。
  - [MASK] 填空: 单 <mask> 句子的 mask 位置 argmax 预测 token
  - 伪困惑度: pseudo-log-likelihood（逐位置 mask 后对真实 token 取 NLL 平均，
    再 exp），即 PLL = exp( mean_j -log P(x_j | x_{\\j}) )

Usage:
    uv run python accuracy_run.py                    # 完整执行 (step1 -> step2)
    uv run python accuracy_run.py --use-pretrained   # Tier2: 加载预训练权重
    uv run python accuracy_run.py --cpu              # 强制 CPU 推理 (禁用 NPU/CUDA)
"""

import argparse
import json
import math
import os
import random
import shutil
import time
from datetime import datetime
from pathlib import Path

# 国内网络环境默认走 HF 镜像（外部已设置的环境变量优先）
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")
os.environ.setdefault("HF_HUB_DISABLE_XET", "1")

import numpy as np
import torch
from transformers import AutoConfig, AutoModelForMaskedLM, AutoTokenizer
from transformers import set_seed as transformers_set_seed

MODEL_ID = "FacebookAI/roberta-base"


def load_benchmark_texts() -> tuple[list[str], str]:
    """加载 MLM 评测文本（每条恰好含一个 <mask>），返回 (texts, dataset_name)。

    MLM 填空/伪困惑度画像：使用内置单 <mask> 常识句（本地无公开
    masked 数据集目录，直接用内置样本）。
    """
    print("[benchmark] using built-in benchmark texts (fill-mask profile)")
    builtin_texts = [
        # ---- 地理/常识 ----
        "The capital of France is <mask>.",
        "The largest planet in our solar system is <mask>.",
        "The Great Wall is located in <mask>.",
        "The river <mask> flows through Egypt.",
        "Mount Everest is the highest <mask> on Earth.",
        "The official language of Brazil is <mask>.",
        "Tokyo is the capital of <mask>.",
        "The Sahara is the largest hot <mask> in the world.",
        "The Pacific is the largest <mask> on Earth.",
        "Berlin is the capital of <mask>.",
        # ---- 科学/自然 ----
        "Water freezes at zero degrees <mask>.",
        "The chemical symbol for gold is <mask>.",
        "Plants use sunlight to make food through <mask>.",
        "The speed of light is about 300,000 kilometers per <mask>.",
        "Humans have <mask> chromosomes in each cell.",
        "The Earth revolves around the <mask> once a year.",
        "The Moon orbits around the <mask>.",
        "Sound travels through the air as <mask>.",
        "The human body needs <mask> to breathe.",
        "Ice is the solid form of <mask>.",
        # ---- 日常/生活 ----
        "I drink a cup of <mask> every morning.",
        "She reads the <mask> to learn the latest news.",
        "He went to the <mask> to buy fresh vegetables.",
        "We use a <mask> to tell the time.",
        "The children play football in the <mask>.",
        "My grandmother bakes delicious <mask> pie.",
        "The doctor gave him a <mask> for the pain.",
        "She took the <mask> to the airport.",
        "He opened the <mask> to let in fresh air.",
        "The restaurant serves Italian <mask>.",
        # ---- 文化/历史 ----
        "William Shakespeare wrote many famous <mask>.",
        "The piano is a musical <mask>.",
        "The Mona Lisa was painted by Leonardo da <mask>.",
        "The Olympic Games are held every four <mask>.",
        "People celebrate Christmas in <mask>.",
        "The first man on the Moon was Neil <mask>.",
        "Beethoven was a famous <mask>.",
        "The ancient pyramids were built in <mask>.",
        "Chess is a game of <mask>.",
        "The violin has four <mask>.",
        # ---- 工作/学习 ----
        "The teacher wrote the answer on the <mask>.",
        "Students must pass the <mask> to graduate.",
        "The meeting will start at nine <mask>.",
        "He works as an engineer at a technology <mask>.",
        "The library has thousands of <mask>.",
        "She finished her homework before <mask>.",
        "The scientist published the results of the <mask>.",
        "The nurse works in a <mask>.",
        "The farmer grows <mask> in the field.",
        "The pilot flew the plane across the <mask>.",
        # ---- 语言/常识推理 ----
        "The opposite of hot is <mask>.",
        "A week has seven <mask>.",
        "There are twelve months in a <mask>.",
        "The color of the sky on a clear day is <mask>.",
        "Birds build their nests in <mask>.",
        "Fish live in the <mask>.",
        "Bees make <mask> from flowers.",
        "A person who writes books is called an <mask>.",
        "The season after winter is <mask>.",
        "We celebrate the new year in <mask>.",
        # ---- 附加（备用） ----
        "The sun rises in the <mask>.",
        "Cats like to drink <mask>.",
        "The football match ended two to <mask>.",
        "She bought a bouquet of <mask>.",
        "The train station is in the center of the <mask>.",
        "He wore a warm coat in <mask>.",
    ]
    return builtin_texts, "builtin"


def select_idle_npu() -> int:
    """选择空闲 HBM 最多的 NPU 并设为当前设备。

    本机禁止设置 ASCEND_RT_VISIBLE_DEVICES（会导致 aclInit error 107001），
    因此通过 torch.npu.set_device() 在多卡中选定单卡。
    """
    count = torch.npu.device_count()
    best_idx, best_free = 0, -1
    for i in range(count):
        try:
            free, _total = torch.npu.mem_get_info(i)
        except Exception:
            free = 0
        print(f"[Device] NPU {i}: free HBM {free / 1024**3:.1f} GiB")
        if free > best_free:
            best_idx, best_free = i, free
    torch.npu.set_device(best_idx)
    return best_idx


def get_device(force_cpu: bool = False):
    """获取推理设备。若 force_cpu=True，强制返回 CPU。

    默认优先级: NPU > CUDA > CPU。
    NPU 多卡时自动选择空闲 HBM 最多的单卡（不设 ASCEND_RT_VISIBLE_DEVICES）。
    """
    if force_cpu:
        return "cpu", 0, "cpu"

    try:
        import torch_npu  # noqa: F401

        if hasattr(torch, "npu") and torch.npu.is_available():
            idx = select_idle_npu()
            device_name = torch.npu.get_device_name(idx)
            return f"npu:{idx}", torch.npu.device_count(), device_name
    except ImportError:
        pass
    if torch.cuda.is_available():
        device_name = torch.cuda.get_device_name(0)
        return "cuda:0", torch.cuda.device_count(), device_name
    return "cpu", 0, "cpu"


class _PerfMonitor:
    """性能监控器：测量推理延迟和峰值内存"""

    def __init__(self, device_type, device_ids=None):
        self.device_type = device_type
        self.device_ids = device_ids
        self.start = None
        self.latency_s = None
        self.peak_memory_mb = None

    def __enter__(self):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401

            torch.npu.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.npu.reset_peak_memory_stats(dev_id)
            else:
                torch.npu.reset_peak_memory_stats()
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                for dev_id in self.device_ids:
                    torch.cuda.reset_peak_memory_stats(dev_id)
            else:
                torch.cuda.reset_peak_memory_stats()

        self.start = time.perf_counter()
        return self

    def __exit__(self, *args):
        if self.device_type == "npu":
            import torch_npu  # noqa: F401

            torch.npu.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.npu.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.npu.max_memory_allocated() / (1024**2)
        elif self.device_type == "cuda":
            torch.cuda.synchronize()
            if self.device_ids is not None:
                max_mem = 0.0
                for dev_id in self.device_ids:
                    mem = torch.cuda.max_memory_allocated(dev_id)
                    max_mem = max(max_mem, mem)
                self.peak_memory_mb = max_mem / (1024**2)
            else:
                self.peak_memory_mb = torch.cuda.max_memory_allocated() / (1024**2)
        else:
            self.peak_memory_mb = 0.0

        self.latency_s = time.perf_counter() - self.start
        return False


def get_profiler_context(device_short):
    """根据硬件动态返回原生 Profiler 上下文"""
    if device_short == "npu":
        import torch_npu  # noqa: F401
        from torch_npu.profiler import ProfilerActivity as NPUActivity
        from torch_npu.profiler import profile as npu_profile

        activities = [NPUActivity.CPU, NPUActivity.NPU]
        return npu_profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)
    else:
        activities = [torch.profiler.ProfilerActivity.CPU]
        if device_short == "cuda":
            activities.append(torch.profiler.ProfilerActivity.CUDA)

        return torch.profiler.profile(activities=activities, record_shapes=True, profile_memory=True, with_stack=True)


def get_dtype_str(dtype: torch.dtype) -> str:
    """Convert torch dtype to short string (fp32, fp16, bf16)."""
    dtype_map = {
        torch.float32: "fp32",
        torch.float16: "fp16",
        torch.bfloat16: "bf16",
        torch.int64: "int64",
        torch.int32: "int32",
    }
    return dtype_map.get(dtype, str(dtype).replace("torch.", ""))


def get_package_versions() -> dict:
    """获取关键依赖包的版本"""
    import importlib.metadata

    packages = ["torch", "transformers", "torch_npu", "numpy", "datasets"]
    versions = {}
    for pkg in packages:
        try:
            versions[pkg] = importlib.metadata.version(pkg)
        except importlib.metadata.PackageNotFoundError:
            versions[pkg] = "not_installed"
    return versions


def setup_model(use_pretrained: bool, device, cache_dir: str):
    """加载模型 (MaskedLM, RoBERTa)"""
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, cache_dir=cache_dir)
    config = AutoConfig.from_pretrained(MODEL_ID, cache_dir=cache_dir)

    if use_pretrained:
        model = AutoModelForMaskedLM.from_pretrained(MODEL_ID, cache_dir=cache_dir)
        model = model.to(device)
    else:
        model = AutoModelForMaskedLM.from_config(config)
        model = model.to(device)
    model.eval()

    return model, tokenizer


def run_step1(model, tokenizer, first_device, device_short, device_ids, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str], num_samples: int):
    """Step 1: 单样本推理 -> trace_*.json + benchmark_metrics_*.json

    MaskedLM 为 encoder-only：单次 forward 即为被 trace 的推理负载。
    """
    print("\n" + "=" * 60)
    print("Step 1: 单样本推理 (性能分析)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    trace_path = adapt_dir / f"trace_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"
    metrics_path = adapt_dir / f"benchmark_metrics_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.json"

    # 单样本（空数据集时使用 fallback）
    text = texts[0] if texts else "The capital of France is <mask>."
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(first_device)

    profiler_context = get_profiler_context(device_short)

    start_time = datetime.now().isoformat()
    with profiler_context as prof:
        with _PerfMonitor(device_short, device_ids) as m:
            with torch.no_grad():
                out = model(**inputs)
                _ = out.logits  # 仅推理，不保存

        latency_s = m.latency_s
        peak_memory_mb = m.peak_memory_mb

    # 导出 trace
    prof.export_chrome_trace(str(trace_path))

    # 获取实际设备型号
    device_model = "unknown"
    if device_short == "npu" and first_device.index is not None:
        device_model = torch.npu.get_device_name(first_device.index)
    elif device_short == "cuda" and first_device.index is not None:
        device_model = torch.cuda.get_device_name(first_device.index)

    # 写入 metrics（end_time/ttft_ms/tpot_ms 将在 main() 末尾更新）
    metrics = {
        "start_time": start_time,
        "latency_s": round(latency_s, 6),
        "peak_memory_mb": round(peak_memory_mb, 2),
        "num_samples": num_samples,
        "device": str(first_device),
        "device_model": device_model,
        "mode": mode_str,
        "dataset": dataset_name,
        "dtype": dtype_str,
        "output_type": "generated_text",
        "packages": get_package_versions(),
    }
    metrics_path.write_text(json.dumps(metrics, indent=2))

    # 清理临时目录（忽略错误，NPU profiler 可能留下文件）
    prof_dir = adapt_dir / "export_only_prof_dir"
    if prof_dir.exists():
        shutil.rmtree(prof_dir, ignore_errors=True)
        print(f"[benchmark] cleaned up {prof_dir}")

    print(f"[benchmark] trace saved to {trace_path}")
    print(f"[benchmark] metrics saved to {metrics_path}")
    print(f"[benchmark] {metrics}")

    return trace_path, metrics_path, start_time


def run_step2(model, tokenizer, first_device, device_short, mode_str, adapt_dir: Path, dataset_name: str, texts: list[str], max_samples: int = 250):
    """Step 2: 全样本推理 -> outputs_*.pt (MaskedLM: fill-mask + 伪困惑度)

    每个样本:
    1. 单次 forward，在 <mask> 位置 argmax 预测 token（fill-mask）并取
       该位置 logits（用于算子精度对比）
    2. 伪困惑度: 对每个非特殊位置逐位 mask，计算真实 token 的 NLL，
       取平均后 exp（pseudo-log-likelihood，上限 32 个位置以控制开销）

    内存优化：
    - 每个样本处理完后立即 .cpu() / del
    - 每 32 个样本清理 NPU/CUDA 缓存

    输出格式 (outputs_*.pt):
    - generated_text: <mask> 位置的预测 token 字符串列表
    - logits: 每个样本 <mask> 位置的 logits 张量列表
    - perplexity: 每个样本的伪困惑度列表

    Returns:
        tuple: (outputs_path, None, None) - 非生成式，不测 TTFT/TPOT
    """
    print("\n" + "=" * 60)
    print("Step 2: 全样本推理 (精度测试: fill-mask + pseudo-PPL)")
    print("=" * 60)

    model_dtype = next(model.parameters()).dtype
    dtype_str = get_dtype_str(model_dtype)

    outputs_path = adapt_dir / f"outputs_{device_short}_{dtype_str}_{mode_str}_{dataset_name}.pt"

    # 限制样本数（R1 规则：最多 250 个样本）
    texts = texts[:max_samples]
    print(f"[benchmark] {len(texts)} samples to process (max {max_samples})")

    vocab_size = model.config.vocab_size
    mask_token_id = tokenizer.mask_token_id
    special_ids = {tokenizer.cls_token_id, tokenizer.sep_token_id, tokenizer.pad_token_id, mask_token_id}

    all_outputs = []
    all_logits = []
    all_ppl = []

    with torch.no_grad():
        for i, text in enumerate(texts):
            inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(first_device)
            input_ids = inputs["input_ids"]
            attention_mask = inputs["attention_mask"]

            # 1. 单次 forward：fill-mask 预测 + mask 位置 logits
            out = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = out.logits  # [1, seq_len, vocab]

            mask_positions = (input_ids == mask_token_id).nonzero(as_tuple=True)
            if len(mask_positions[1]) == 1:
                mask_pos = int(mask_positions[1][0])
                mask_logits = logits[0, mask_pos]
                predicted_id = int(mask_logits.argmax(dim=-1))
                predicted_token = tokenizer.decode([predicted_id])
                all_outputs.append(predicted_token)
                all_logits.append(mask_logits.cpu())  # [vocab_size]
            else:
                # 退化情况（无 <mask>）：占位保持样本对齐
                all_outputs.append("")
                all_logits.append(torch.zeros(vocab_size, dtype=torch.float32))
            del out, logits

            # 2. 伪困惑度（pseudo-log-likelihood）
            seq_len = int(input_ids.shape[1])
            positions = [j for j in range(seq_len) if int(input_ids[0, j]) not in special_ids]
            positions = positions[:32]  # 上限 32 个位置以控制开销
            if positions:
                nll_sum = 0.0
                for j in positions:
                    masked_ids = input_ids.clone()
                    masked_ids[0, j] = mask_token_id
                    m_out = model(input_ids=masked_ids, attention_mask=attention_mask)
                    log_probs = torch.log_softmax(m_out.logits[0, j], dim=-1)
                    nll_sum += -log_probs[int(input_ids[0, j])].item()
                    del m_out, log_probs
                pseudo_ppl = math.exp(nll_sum / len(positions))
                all_ppl.append(pseudo_ppl)
            else:
                all_ppl.append(float("nan"))

            del inputs, input_ids, attention_mask

            # 每 32 个样本清理缓存（更频繁以避免 OOM）
            if (i + 1) % 32 == 0:
                if device_short == "npu":
                    torch.npu.empty_cache()
                elif device_short == "cuda":
                    torch.cuda.empty_cache()
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples (cache cleared)")

            elif (i + 1) % 8 == 0:
                print(f"[benchmark] processed {i + 1}/{len(texts)} samples")

    # 保存 outputs（含 fill-mask 预测、mask 位置 logits、伪困惑度）
    output_data = {
        "generated_text": all_outputs,
        "logits": all_logits,
        "perplexity": all_ppl,
    }
    torch.save(output_data, outputs_path)

    # PPL 统计
    ppl_avg = round(sum(all_ppl) / len(all_ppl), 2) if all_ppl else None

    print(f"[benchmark] outputs saved to {outputs_path}")
    print(f"[benchmark]   - generated_text (mask fills): {len(all_outputs)} samples")
    if all_logits:
        print(f"[benchmark]   - logits: {len(all_logits)} samples, shape: {all_logits[0].shape}")
    print(f"[benchmark]   - pseudo-perplexity: avg={ppl_avg}")
    for k in range(min(5, len(all_outputs))):
        print(f"[benchmark]   sample[{k}]: '{texts[k]}' -> '{all_outputs[k]}' (ppl={all_ppl[k]:.2f})")

    return outputs_path, None, None  # 非生成式，不测 TTFT/TPOT


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--use-pretrained", action="store_true", help="Tier2: load pretrained weights")
    parser.add_argument("--max-samples", type=int, default=250, help="Max samples to process (default 250, per R1 rule)")
    parser.add_argument("--cpu", action="store_true", help="Force CPU inference (disable NPU/CUDA)")
    args = parser.parse_args()

    CACHE_DIR = (Path(__file__).resolve().parent / "models").as_posix()
    ADAPT_DIR = Path(__file__).resolve().parent

    # 1. Seed
    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    transformers_set_seed(SEED)
    device, _, _ = get_device(force_cpu=args.cpu)
    if device.startswith("npu"):
        torch.npu.manual_seed_all(SEED)
    elif device.startswith("cuda"):
        torch.cuda.manual_seed_all(SEED)

    # 开启全局确定性算法（确保 CUDA/NPU 输出一致）
    torch.use_deterministic_algorithms(True, warn_only=True)

    # 仅在非 --cpu 模式下检查设备
    if not args.cpu:
        assert device.startswith(("npu", "cuda")), f"Need NPU or CUDA, got {device}"

    # 2. Load dataset
    texts, dataset_name = load_benchmark_texts()
    print(f"[benchmark] using dataset: {dataset_name}, total samples: {len(texts)}, max_samples: {args.max_samples}")

    # 3. Model
    model, tokenizer = setup_model(args.use_pretrained, device, CACHE_DIR)

    first_device = next(model.parameters()).device
    device_short = str(first_device).replace(":", "_")
    perf_device_short = first_device.type
    mode_str = "pretrained" if args.use_pretrained else "config"

    # 实际参与统计的样本数（与 Step 2 截断保持一致）
    num_samples = min(len(texts), args.max_samples)

    # 提取设备 IDs
    device_ids = None
    if hasattr(model, "hf_device_map"):
        device_ids = list(set(dev.index if hasattr(dev, "index") else dev for dev in model.hf_device_map.values()))
    elif first_device.index is not None:
        device_ids = [first_device.index]

    # Step 1: 单样本 -> trace + metrics
    trace_path, metrics_path, start_time = run_step1(model, tokenizer, first_device, perf_device_short, device_ids, mode_str, ADAPT_DIR, dataset_name, texts, num_samples)

    # Step 2: 全样本 -> outputs（非生成式，无 TTFT/TPOT）
    outputs_path, ttft_avg, tpot_avg = run_step2(model, tokenizer, first_device, perf_device_short, mode_str, ADAPT_DIR, dataset_name, texts, args.max_samples)

    # 更新 metrics 文件（添加 end_time, ttft_ms, tpot_ms）
    end_time = datetime.now().isoformat()
    with open(metrics_path, "r") as f:
        metrics = json.load(f)

    metrics["end_time"] = end_time
    metrics["ttft_ms"] = ttft_avg
    metrics["tpot_ms"] = tpot_avg

    with open(metrics_path, "w") as f:
        json.dump(metrics, indent=2, fp=f)

    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"  ✅ trace: {trace_path}")
    print(f"  ✅ metrics: {metrics_path}")
    print(f"  ✅ outputs: {outputs_path} (含 generated_text + logits + pseudo-perplexity)")

    print(f"\n💡 To analyze NPU fallback, run:")
    print(f"   uv run python benchmark/scripts/benchmark_tool.py trace {trace_path.name}")


if __name__ == "__main__":
    main()
